### ISSUE TITLE
Default timeouts for HttpClient not sufficient for simple upload

### ISSUE THREAD

**Issue by ginach** [OneDrive/onedrive-sdk-csharp#10]
SO link: http://stackoverflow.com/questions/33408692/cannot-upload-to-onedrive-using-the-new-sdk

By default, HttpClient has a timeout of 100s. For simple upload, which can be a long-running action, this timeout is not sufficient and can result in task cancellation exceptions. We need to default to a higher value and give the developer a way to override.

**Comment by Miittcchhzz** [comment]
Im also looking at this issue of 100s capped timeout for uploads. I see you have changed the HTTPProvider class with a setTimeout method, can you provide me with a sample of how i can call this method from the API? (currently on 1.1.15)

**Comment by ginach** [comment]
Timeout can now be specified on the client.

**Comment by boyinghu** [comment]
@ginach , do you mean specifiy timeout via OneDriveClient? but i cannot find the relevant property or method. could you please provide more details?

**Comment by flaviosuardi** [comment]
hi @ginach,
as @boyinghu  ask, could you please specify property or method to override timeout on OneDriveClient?
Thanks.

**Comment by ginach** [comment]
@flaviosuardi, the change was to add a OverallTimeout property on HttpProvider to allow changing the default timeout on the enclosed HttpClient.

**Comment by flaviosuardi** [comment]
@ginach thanks a lot!
