### ISSUE TITLE
Authenticating a user from a C# wpf application given email address and password

### ISSUE THREAD

**Issue by videoguy** [OneDrive/onedrive-sdk-csharp#101]
Hi
We have a WPF application that wants to provide access to its functionality if user can authenticate using Microsoft account credentials. The application has set of MS account email addresses (a white list) that are allowed to use the functionality.
I am wondering if there is a way to authenticate these MS accounts using our own user interface.
What I am looking for is a method like below that takes a email address and password and return true or false (i.e. return true if password matches for that email address).

    bool AuthenticateAccount(string ms_acct_email_address, string password)

From what I understand, Onedrive (or Live connect before this) sdk pops up a browser window to do authentication. I am wondering if there is a way to authenticate with our own login user interface.

Thanks

**Comment by ginach** [comment]
There is not. Microsoft account OAuth requires that the Microsoft-rendered UI be presented to the user so they can trust the source.

**Comment by videoguy** [comment]
This application runs in an environment where browser engine is not present.
Do you have suggestions for us to try?

**Comment by ginach** [comment]
The only real approach would be to store the refresh tokens in your database and authenticate a client silently using those. Our [webhooks sample](https://github.com/rgregg/onedrive-webhook-sample/tree/dev) is an example of an app that does this.

**Comment by rgregg** [comment]
For work/school accounts, you can also user the OAuth2 password flow if you have specific requirements for it: http://www.cloudidentity.com/blog/2014/07/08/using-adal-net-to-authenticate-users-via-usernamepassword/

This is not available for consumer accounts however.

**Comment by videoguy** [comment]
We have an application that runs on Win10 systems. Imagine the system has 10 users with each user using MSA to login to their system. Like mary@yahoo.com, jane@outlook.com MSA accounts to login. For whatever reason, the system got into weird state and is unstable to use. Now user is redirected to boot into Windows RE based OS in a hidden partition. As part of our solution, we like to authenticate the user before he or she is given access to advanced diagnostics tools (including access to cmd shell). Our app already knows the email ids of each MSA on the system. What we like to do is  prompt the user for password and silently authenticate with MSA backend.

I checked the link. It looks like the perfect api for what we are looking for. But it is tied to ADAL. I am not sure how I can tie it back to MSA though. I wish MSA provides a way to do this. Here our goal is not to access assets of the user in the backend. I believe that is the reason why OneDisk wants an interactive popup with content coming from MS backend to get user consent. Here we have an application that wants to authenticate local windows user (that is tied to MSA) using MSA backend.
WinRE doesn't have reliable browser engine. Even if there is one, it is hard sell convincing our user experience team that we need to show browser popup with user experience that we have no control over. 

Thanks for pointers!
