### ISSUE TITLE
Delta request errors are not returned with useful properties

### ISSUE THREAD

**Issue by dkonigsberg** [OneDrive/onedrive-sdk-csharp#102]
This is in reference to the API request documented here:
https://dev.onedrive.com/items/view_delta.htm

When I do a Delta request using the SDK, there are cases where the server will return an error.  These error responses include various codes (e.g. "resyncRequired", "resyncApplyDifferences", etc), and a Location header telling me how to construct my next request.

The SDK's API, however, just gives me a generic OneDriveException.  This exception contains error strings I can compare against to check the code values (though an actual parsed enum would be nicer), and that's it.  The exception does not contain the Location header, or any error response headers at all.

My local quick-fix for this problem, was to modify the SDK to include the HTTP Headers object from the error response as part of the OneDriveException.

**Comment by daspek** [comment]
Hi Derek,
You shouldn't need to use anything from the headers. The Location header is there for consistency with some other Microsoft API's, but it's not really necessary. When you get a ResyncRequired error, you just need to start sync again from scratch (without a token), following the instructions defined in the docs.

**Comment by dkonigsberg** [comment]
Thanks. This approach works. However, the HTTP API docs seemed to indicate that I should be using the Location header. Perhaps the docs need to be updated to indicate that its only for compatibility purposes.
