### ISSUE TITLE
Need hook for setting custom request headers

### ISSUE THREAD

**Issue by dkonigsberg** [OneDrive/onedrive-sdk-csharp#103]
On Windows Phone Silverlight, the System.Net.Http library does not expose the necessary APIs for controlling cache behavior. In addition, it does appear to do some amount of request caching by default. This has caused big problems in our testing of OneDrive.

The solution we found, was to add an extra header to each request, to force a no-cache behavior. Locally, the fix consisted of modifying BaseRequest.cs as such:
```
private void AddHeadersToRequest(HttpRequestMessage request)
{
    . . .
    . . .
    request.Headers.Add("Cache-Control", "no-cache");
}
```

If there's a cleaner way of doing this, that doesn't require modifying the SDK, I'd like to know.  If not, it would be nice if the SDK had hooks for adding a necessary common header like this (or a way of defining Windows Phone specific request properties).

**Comment by ginach** [comment]
The SDK is already setting Cache-Control to no-store, no-cache by default on every request in the HttpProvider layer. I take it you're using a custom IHttpProvider?

The Request() method on the request builders takes in a collection of request options, which can be either HeaderOption or QueryOption objects. HeaderOption objects will be added to the request headers on send. Another option is to call request.GetHttpRequestMessage() to get the request message (minus authentication headers) that you can modify however you want. Calling client.AuthenticationProvider.AppendAuthHeaderAsync(requestMessage) will append the auth header. Then you can send the request using the IHttpProvider instance on the client.

**Comment by dkonigsberg** [comment]
Thanks for pointing this out.  The previous version of the SDK (onedrive-explorer-win) did not have this code, so I didn't notice that the new SDK does have it.  (was looking in the wrong place)  Will close this issue.
