### ISSUE TITLE
OneDrive for Business Support

### ISSUE THREAD

**Issue by dgp1130** [OneDrive/onedrive-sdk-csharp#11]
Is there anyway to utilize this SDK for OneDrive for Business? The authentication seems to assume consumer OneDrive, is there a way to way to change this behavior so I can login to a business account? If not, can authentication be done separately but still use the SDK for the API calls afterwards?

**Comment by ginach** [comment]
Not yet but the feature is currently in development and should be available soon.

**Comment by ginach** [comment]
Version 1.1.0 of the SDK we release today now includes OneDrive for Business support.
