### ISSUE TITLE
Always Asking for Permissions

### ISSUE THREAD

**Issue by erfg12** [OneDrive/onedrive-sdk-csharp#111]
This logs in and asks for permissions and displays the root folder contents just fine, but every time I launch the program it asks for permissions. How can I get it to stop?

I don't see anything in their samples different from what I'm doing. But, it's possible I over looked something.

```
private IOneDriveClient oneDriveClient { get; set; }
private static readonly string[] oneDriveScopes = 
{
    "wl.signin", 
    "wl.offline_access", 
    "onedrive.readwrite"
};

private async Task oneDriveLogin()
{
    if (oneDriveClient == null)
    {
        oneDriveClient = OneDriveClient.GetMicrosoftAccountClient(
            "APP_CID_HERE", 
            @"https://login.live.com/oauth20_desktop.srf", 
            oneDriveScopes, 
            webAuthenticationUi: new FormsWebAuthenticationUi());

        try
        {
            if (!oneDriveClient.IsAuthenticated)
                await oneDriveClient.AuthenticateAsync();
        }
        catch (OneDriveException exception)
        {
            // Swallow authentication cancelled exceptions
                    if (!exception.IsMatch(OneDriveErrorCode.AuthenticationCancelled.ToString()))
                    {
                        if (exception.IsMatch(OneDriveErrorCode.AuthenticationFailure.ToString()))
                        {
                            MessageBox.Show(
                                "Authentication failed",
                                "Authentication failed",
                                MessageBoxButtons.OK);

                            var httpProvider = this.oneDriveClient.HttpProvider as HttpProvider;
                            httpProvider.Dispose();
                            this.oneDriveClient = null;
                        }
                    }
        }
    }
}
```

Found the answer - http://stackoverflow.com/questions/36775920/how-do-i-login-to-onedrive-after-the-initial-time-without-seeing-the-permissio

Can you put this in one of your example projects please so everyone knows how to do this.

**Comment by ginach** [comment]
@erfg12, that is one approach. Our [webhook sample](https://github.com/rgregg/onedrive-webhook-sample/tree/dev) uses that approach but you're right that it's not linked off the SDK documentation. I'll add it.

The other approach is to make use of the caching in the SDK. The SDK uses a client-side cache that the app can store and use when initializing the client. The app would call the GetCacheBlob() method of CredentialCache to get the byte array representation of the cache for the app to store. You can pass the blob to the constructor of CredentialCache and send the cache instance to the client at creation. This is modeled after caching in [ADAL](http://www.cloudidentity.com/blog/2013/10/01/getting-acquainted-with-adals-token-cache/). You do need to specify the user ID at client creation as well but that can also be passed to the client creation extension method.
