### ISSUE TITLE
Update item use "Content" property throw exception

### ISSUE THREAD

**Issue by jingliancui** [OneDrive/onedrive-sdk-csharp#113]
Hello , I follow your docs' item doc :[https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/items.md#moving-and-updating-an-item](url)
update the file it ok,
but I update the Item's **Content** property with **Stream**,It's throw exception.
Is it has other way for me to update the Item's Content which is stream.

**Comment by ginach** [comment]
@jingliancui, could you provide more details about what exception you're seeing?

**Comment by jingliancui** [comment]
@ginach ，There is the error message:
**The API 'System.IO.BufferedStream.get_CanRead()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.**

My app's platform is the universal windows app.
There is something image for you :
Hope that message will help you 

![errormessage](https://cloud.githubusercontent.com/assets/16309962/15446786/b6e7f200-1f5d-11e6-9b0d-25d2835706b0.png)
![3](https://cloud.githubusercontent.com/assets/16309962/15446785/b6e6d208-1f5d-11e6-826d-f0d267987126.png)
![1](https://cloud.githubusercontent.com/assets/16309962/15446804/fb62d512-1f5d-11e6-94b0-b105172040a0.png)
![2](https://cloud.githubusercontent.com/assets/16309962/15446787/b6ecbfe2-1f5d-11e6-836b-f07e5ef58e7c.png)

**Comment by ginach** [comment]
This is a weird one but I'm not sure if it's a bug in our code or JSON.NET. I'll need to dig in further.

**Comment by ginach** [comment]
Ah, I see what's happening here. The update call you're making is to update item metadata. We don't actually support sending metadata and stream in that way on the service side. Instead, what you'll want to do is update item content using the /content navigation. For example:

```csharp
var updatedItem =
    await this.oneDriveClient.Items[id].Content.Request().PutAsync<Item>(stream);
```
Also, you'll want the stream to be one that supports reading and seeking. For example, a file stream or memory stream.
