### ISSUE TITLE
Access public folder

### ISSUE THREAD

**Issue by jcmag** [OneDrive/onedrive-sdk-csharp#118]
Hi,
I'd like to know if it is possible to access a public shared folder without authenticating the user (just using the shared folder link)

**Comment by ginach** [comment]
The API doesn't yet support accessing items via shared links so neither does the SDK.

That said, you can send unauthenticated requests using your own IAuthenticationProvider implementation that essentially returns no-op tasks from each of the methods and stubs out the other properties.
