### ISSUE TITLE
Accessing SharePoint document libraries - configuration?

### ISSUE THREAD

**Issue by datapool99** [OneDrive/onedrive-sdk-csharp#119]
The documentation states 

> "To use OneDrive API with SharePoint document libraries, you need to know the SharePoint site's URL"

If I set the additional parameter **ActiveDirectoryServiceResource** for client setup:

```
oneDriveClient = BusinessClientExtensions.GetClient(
                            new BusinessAppConfig
                            {
                                ActiveDirectoryAppId = AadClientId,
                                ActiveDirectoryReturnUrl = AadReturnUrl,
                                ActiveDirectoryServiceResource = @"https://{tenant}.sharepoint.com/"
                            });
```

The authorization code flow works fine and I get the client with refresh token back - so it looks like that the auhtorization to get the sharepoint site client works fine.

However, I am not able to list folders/files as I am doing exactly the same with the OneDrive Business API SDK call. The business API works fine with the following SDK call:

`folder = await oneDriveClient.Drive.Root.Request().Expand("children").GetAsync();`

But this call failes when using the SharePoint URL mentioned above with the following exception

> OneDrive reported the following error: Code: -214024891, System.UnauthorizedAccessException

However, the user has the same access to that sharepoint as to his onedrive business account.  And the same procedure works when just using the onedrive business account. Does the app permissions need to be changed/configured in the AzureAD portal to use Office365 SharePoint sites? The app has setup as mentioned in your documentation, and works fine with the OneDrive Business as shown in your sample code. Just not with the SharePoint URL as ServiceRessource.

The documentation is very short with only sentence above and there is no documentation on how to list the folders/files with the SDK when using the sharepoint URL.

**Comment by ginach** [comment]
@datapool99, you'll need to set the base URL for the SharePoint site as well. For example:

```csharp
oneDriveClient = BusinessClientExtensions.GetClient(
    new BusinessAppConfig
    {
        ActiveDirectoryAppId = AadClientId,
        ActiveDirectoryReturnUrl = AadReturnUrl,
        ActiveDirectoryServiceResource = @"https://{tenant}.sharepoint.com/",
        ActiveDirectoryServiceEndpointUrl = @"https://{tenant}.sharepoint.com/_api/v2.0/{siteId}",
                            });
```

The lack of documentation in this case is due to the fact that this is possible but it's not a use case we want to advertise. Let me follow up on if this is still the case or if we want to document it after all.

**Comment by datapool99** [comment]
Thanks for the update. However, if I add this, I get a `System.UnauthorizedAccessException` error.
Are there some rights the need to be added in addition? Can you give me a hint where to get the `{siteID}` ?

**Comment by datapool99** [comment]
@ginach,  thanks for the update. The login works. However, after login and trying to get the folders with the standard call, I get a `System.UnauthorizedAccessException` error. I am using the following call - which returns the access error:

`folder = await oneDriveClient.Drive.Root.Request().Expand("children").GetAsync();`

I am using the same for the Business Client which works fine. And the sharepoint site exists with folders in it for the user. Not sure what needs to be done or adjusted? Does this call not work with sharepoint? Are there additional parameter that need to be set? Maybe I am using a wrong {siteId}, can you tell me how to check if it is a correct siteId?

**Comment by datapool99** [comment]
After hours of try & error, I found out the following. Just to mention for others that might run into this issue:

First, it looks like the base URL needs to be formated this way:
`ActiveDirectoryServiceEndpointUrl = @"https://{tenant}.sharepoint.com/{siteId}/_api/v2.0/`
NOT
`ActiveDirectoryServiceEndpointUrl = @"https://{tenant}.sharepoint.com/_api/v2.0/{siteId}`

Second you need to make sure that your app, which has to be registered in the Azure Active Directory portal, has additional rights set to browse the sharepoint. https://manage.windowsazure.com/

With these two steps, I got the onedrive SDK to work with the office365 online sharepoint and acces the folder and files exactly the same as the drive.

**Comment by ginach** [comment]
Glad you figured it out!
