### ISSUE TITLE
CreateFolder issue

### ISSUE THREAD

**Issue by nsouren** [OneDrive/onedrive-sdk-csharp#122]
Based on the documentation (https://dev.onedrive.com/items/create.htm)
there is "@name.conflictBehavior" query option available when creating a folder.
But regardless of which value for the option is provided, SDK always failing to create a folder, if it is already exists ("rename" does not work). This is true, if you signed in with "Business" account. If you signed in with "Personal" account, the call to CreateFolder always returns the instance of an already existing folder with the same name ("rename" and "fail" options do not work).

**Comment by ginach** [comment]
Thank you for reporting this. This sounds like an API issue so I've moved it over to the [API docs repo](https://github.com/OneDrive/onedrive-api-docs/issues/391).
