### ISSUE TITLE
DELETE request deletes file permanently

### ISSUE THREAD

**Issue by mulawam** [OneDrive/onedrive-sdk-csharp#123]
Submitting DELETE request removes item from OneDrive for Business permanently and I cannot locate this item in Recyle Bin or even Second-stage recycle bin. When items are deleted directly from the OneDrive for Business UI they are added to Recycle Bin. 

`DELETE https://{tenant}-my.sharepoint.com/_api/v2.0/drive/items/{itemId}`

This is not inline with the documentation from https://dev.onedrive.com/items/delete.htm.

> ... using this method will move the items to the Recycle Bin

**Comment by ginach** [comment]
Thanks for reporting this. Unfortunately, this is an API bug and not an SDK bug so I'm going to close this issue and reopen [the issue in the API docs repo](https://github.com/OneDrive/onedrive-api-docs/issues/389#event-688472093).
