### ISSUE TITLE
AuthenticationCancelled exception

### ISSUE THREAD

**Issue by Joker8991** [OneDrive/onedrive-sdk-csharp#124]
Hello,
When I cancel an authentication, the raised Exception doesn't match "OneDriveErrorCode.AuthenticationCancelled" but "OneDriveErrorCode.AuthenticationFailure"
this is a bug or am I doing something wrong?

Thank you

**Comment by ginach** [comment]
Hi @Joker8991, which method are you using to create your client?

**Comment by Joker8991** [comment]
Hi, @ginach, I used `oneDriveClient = OneDriveClientExtensions.GetUniversalClient(scopes);` and then `oneDriveClient.AuthenthicateAsync()` for the authentication.

**Comment by ginach** [comment]
Closing issue. This will be fixed in the next package update.
