### ISSUE TITLE
Access to file in root

### ISSUE THREAD

**Issue by vasellivittorio** [OneDrive/onedrive-sdk-csharp#125]
Hi i receive this exception when try to access to a file in root of my OneDrive:

`{Code: invalidRequest
Throw site: 0f1c.0271
Message: Paths can only contain at most two colons

Inner error
Code: badRequest
Throw site: 0f1c.0271
}`

I am using this code:
`var item = await oneDriveClient
                     .Drive
                     .Root
                     .ItemWithPath("/drive/root:/MyFile.txt")
                     .Request()
                     .GetAsync();`

**Comment by ginach** [comment]
Correct, you'll only want to pass the Myfile.txt value to ItemWithPath. Drive.Root will add the /drive/root to the request and ItemWithPath will add the colons.
