### ISSUE TITLE
Option vs QueryOption

### ISSUE THREAD

**Issue by BobDeCuir** [OneDrive/onedrive-sdk-csharp#126]
The BaseRequest constructor has an optional IEnumerable[Option] but it only parses [QueryOptions] from the enumerable.

There is no way to pass an IList[QueryOption] to any class based on the BaseRequest including ItemContentRequest. Because of this, there doesn't appear to be a way to add additional query parameters like "name.conflictBehavior" on any requests.

**Comment by BobDeCuir** [comment]
It is possible to create a List[Option] then add to the list a new QueryOption(string, string) - which works.

**Comment by ginach** [comment]
It's a miss that Option isn't an abstract class. You'll want to pass in QueryOption objects to add query options and HeaderOption objects for adding headers.
