### ISSUE TITLE
how get parameter RefreshToken without a first authentication ?

### ISSUE THREAD

**Issue by patrikLimaPereira** [OneDrive/onedrive-sdk-csharp#134]
how get parameter RefreshToken without a first authentication ?

I am try to using  method OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient () in  onedrive-sdk-csharp (windowns form)

my aplication is a service windows. therefore during reboot of the computer my aplication need to start alone.

I need sign in "onedrive" 100% automatic

the documentation in " https://dev.onedrive.com/auth/msa_oauth.htm" no explains for in  onedrive-sdk-csharp (windowns form)

**Comment by cdmayer** [comment]
Refresh token is provided when authenticating. Its function is to renew an existing session - so you have to have an established session first. There is no way to get a refresh token without authenticating once first.

However, using the method you are referencing does not require a refresh token. The first time that you authenticate the app, you can pass in an empty string in the `refreshToken` field. That will force a new session to be created. Later, you can pass in the `refreshToken` you have for a user, and the client will renew the session (which is faster than starting a new session).
