### ISSUE TITLE
Signing key rollover in Azure Active Directory

### ISSUE THREAD

**Issue by opicko** [OneDrive/onedrive-sdk-csharp#136]
I received a warning email from the "azure team" stating that the Azure active directory certificate associated with on of my applications will roll over which will result in downtime if action is not taken!

it recommended  review you applications to ensure they support automatic certificate rollover?

How should this be  handled using the SDK?

**Comment by cdmayer** [comment]
The SDK does not handle certificates. I would recommend that you follow the directions provided in the email.
