### ISSUE TITLE
Authentication on Xamarin

### ISSUE THREAD

**Issue by ronnie-kleinfeld** [OneDrive/onedrive-sdk-csharp#143]
Hi
I'm trying to use the nuget in Xamarin but I keep getting problems with the login ui that is not showing

Do you have a working sample for xamarin?

**Comment by cdmayer** [comment]
Not currently. You would need to create a new class that implements `IAuthenticationProvider` using the appropriate UI code for Xamarin. If you do make such a class please submit a pull request!

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
