### ISSUE TITLE
Accessing Shared Content via /shares/{shareId}/root

### ISSUE THREAD

**Issue by DamirLisak** [OneDrive/onedrive-sdk-csharp#147]
I want to access shared content which is described at:
https://dev.onedrive.com/shares/shares.htm
The example shows that "/root" must be included to access the childs:
GET /shares/{sharingTokenOrUrl}/root?expand=children

The interface IShareRequestBuilder doesn't have a "Root"-property . Instead of this it has the property "IItemsCollectionRequestBuilder Items" which can't be used according to the API-Documentation.

For testing purposes I encoded the sharingTokenOrUrl and appended "/root" :
var request = _OneDriveClient.Shares[encodedUrl + "/root"].Request().Expand("children");

I get a result, but now, there is no IItemRequestBuilder-Interface or similiar which can deserialize the JSON-Result from the AdditionalData-Property for accessing the Items (and uploading and downloading the content afterwards)

Is somebody already working on this missing feature?

**Comment by DamirLisak** [comment]
@cdmayer:
Hi,
do you know when the Invitation-Action (https://dev.onedrive.com/items/invite.htm) will be implemented?
(I know it's a preview - with the risk some things will be changed - but for my project it would be a very useful feature)
Or is there another way to limit the access to some people in a group to a shared folder programatically (As far as I understand the undocumented IPermissionRequest.CreateAsync()-Method it's not possible to add a permission without knowing the userid. In my case I only know the e-Mail-Address) ?

**Comment by cdmayer** [comment]
Fixed in #182. https://www.nuget.org/packages/Microsoft.OneDriveSDK/2.0.3
