### ISSUE TITLE
backup and Restore to one drive for business 

### ISSUE THREAD

**Issue by praveenmb9752000** [OneDrive/onedrive-sdk-csharp#151]
Hi, 
I am developing an application to backup folders, files and Recycling bin(probably in the future Recent, Shared with Me, Discover items as well) and Also to restore these same files back .
For Back up, I need to get the version history properties of the files as well. 

Note that I will get Access Token from the another REST endpoint directly, so I will not be provided with the ClientID, Client Secret Key, Redirect URL to directly create OneDriveClient from One Drive SDK(I know that this is answered in another thread.)

Which way to go?either to use REST APIs? or One Drive SDK or Sharepoint SDK?

**Comment by cdmayer** [comment]
This is not currently supported in the API. You can open an issue here: https://github.com/OneDrive/onedrive-api-docs
