### ISSUE TITLE
General Exception for exapand=Children

### ISSUE THREAD

**Issue by praveenmb9752000** [OneDrive/onedrive-sdk-csharp#155]
Hi ,

I am invoking below URL, but getting "generalException"
Request:
GET https://<Tenant>-my.sharepoint.com/personal/<User>/_api/v2.0/drive/root/view.delta?expand=children
Repsonse:
{
  "error": {
    "code": "generalException",
    "message": "An unspecified error has occurred."
  }
}

**Comment by cdmayer** [comment]
Please open this issue against the API Docs, as this is not an SDK-specific issue. https://github.com/OneDrive/onedrive-api-docs
