### ISSUE TITLE
Time out   in 1 minutes and 40 seconds upload large file

### ISSUE THREAD

**Issue by patrikLimaPereira** [OneDrive/onedrive-sdk-csharp#156]
how to solve this problem?

![error](https://cloud.githubusercontent.com/assets/18745406/18006081/40253340-6b74-11e6-92ac-dd7e0124192f.jpg)

**Comment by cdmayer** [comment]
You could add some retry logic to `HttpProvider` so that when it tries to send a request and receives a timeout error, you can resend the request (limit it to some finite number, maybe 3-4 retries). That can be helpful when timeouts abound.
