### ISSUE TITLE
Version 2.0 - first reviewscx

### ISSUE THREAD

**Issue by patrikLimaPereira** [OneDrive/onedrive-sdk-csharp#157]
in version 2.0 to implement the code below

`IOneDriveClient oneDriveClient = await OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(msaClientId, msaReturnUrl, scopes, getRefreshToken());
`

The version change much modified the code structure.

Migration from version 1.x to 2.x had been costly and too time consuming for you guys did not keep the structure of the code?

I know ginach did not do a good job, but do not follow the initial standard API is a lack of respect for the developers.

In addition, the developers need a document to winform better.

What is the final date that onedrive supports access from 1.x based API?

**Comment by cdmayer** [comment]
Version 1,2 is still available in [this repository](https://github.com/OneDrive/onedrive-sdk-csharp/releases/tag/1.2.0)  and in [Nuget](https://www.nuget.org/packages/Microsoft.OneDriveSDK/). If you do not wish to move up to version 2.x at this time then you should be able to use those versions I linked. Let me know if you need help there.
