### ISSUE TITLE
OneDriveClientExtensions missing in ver 2.0

### ISSUE THREAD

**Issue by kdn29** [OneDrive/onedrive-sdk-csharp#159]

**Comment by MannusEtten** [comment]
yeah i found the same issue, now is my code broken :-(

in the documentation you cant find anything about it because it is not up to date

**Comment by ryanwinter** [comment]
Also missing OneDriveClientExtensions.GetClientUsingOnlineIdAuthenticator. Used this for single sign on from windows 10 devices.

**Comment by cdmayer** [comment]
At this time those have not been ported to V2. You should be able to keep using V1,2 at this time.

@MannusEtten Can you point to what part of the documentation that is out of date? I'll make sure to update anything that is dated.

**Comment by MannusEtten** [comment]
the documentation about how to use the SDK in version 2.0 because now it is all pointing to the extension classes

**Comment by Mogikan** [comment]
For those like me replace OneDriveClientExtensions.GetClientUsingOnlineIdAuthenticator(Scopes) with
var onlineIdProvider = new OnlineIdAuthenticationProvider(Scopes);
await onlineIdProvider.RestoreMostRecentFromCacheOrAuthenticateUserAsync();
var client = new OneDriveClient("https://api.onedrive.com/v1.0", onlineIdProvider);
Not sure what is the problem not to break backward compatibility.

**Comment by olumide-oyetoke** [comment]
@cdmayer it seems ver 2.x is still lacking in functionality since 2016.
Please when will it be ported?
