### ISSUE TITLE
Can't get item thumbnail's

### ISSUE THREAD

**Issue by yuribb** [OneDrive/onedrive-sdk-csharp#165]
Hello. 

I'm working with OneDrive SDK for business office 365 client. I try to get a file thumbnail. When i try to get file thumbnails I get an error timeout with NotImplemented status code.

Request for thumbnails is:
https://{tenant}.sharepoint.com/_api/v2.0/drives/{driveId}/items/{itemId}/thumbnails

**Comment by cdmayer** [comment]
Not an issue with the SDK. Please post an issue here: https://github.com/OneDrive/onedrive-api-docs/issues
