### ISSUE TITLE
[v2] Session expires

### ISSUE THREAD

**Issue by tgckpg** [OneDrive/onedrive-sdk-csharp#172]
In OneDrive SDK v2, session will expires on a very short period of time even when using `CredentialVault` ( about 1 ~ 2 hours ).
However in SDK v1, session never expires.

This is inconvenient because it require user to re-enter their credential every time they open my app ( it is a store app ).

For now I'll be falling back into v1.

FYI, [here's the relevant commit I've used for v2](https://github.com/tgckpg/libwenku8/commit/cd5d6f814125fe1bc0d6b6aa4f696b70636e977c)

**Comment by cdmayer** [comment]
Take a look at [v1-maintenance](https://github.com/OneDrive/onedrive-sdk-csharp/tree/v1-maintenance). 

`CredentialVault` is supposed to hold your session then renew it automatically. It won't work if you don't request the `offline_access` scope and provide the client secret. Have you tried that?

**Comment by tgckpg** [comment]
Adding the `wl.offline_access` scope will add the permission:
- **Access your Info anytime**.

Which is a bit misleading for the users because they might think I am accessing their personal info, **anytime**.
In fact, I just want my app to do things on it's own folder only.

In v1, I didn't need to define `wl_offline_access` to have the session automatically renewed.

Anyway, was there a policy changes so that I MUST have the `wl.offline_access` scope defined ( in order to have session auto renewed ) ? If that's the case I might need to stay in v1 until the support has ended.

**Comment by cdmayer** [comment]
I see. You are basically asking for [OnlineIdAuthenticator support](https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter/issues/9). That is high on the list right now.

The documentation you linked to is for the Live SDK, which is deprecated.
