### ISSUE TITLE
Invalid request for Drive.Items.Request.GetAsync()

### ISSUE THREAD

**Issue by shomarisharpe** [OneDrive/onedrive-sdk-csharp#175]
Hi,
I believe this is a bug since the return is a collection (which i believe is the children of the "root" item.

so OneDriveClient.Drive.Items.Request.GetAsync() should be equivalent to OneDriveClient.Drive.Root.Children.Request.GetAsync()

However when I execute OneDriveClient.Drive.Items.Request.GetAsync() i get "Invalid Request"

**Comment by cdmayer** [comment]
Those requests are not equivalent. Drive.Items uses Item.Id as a key, as opposed to path. You can learn more [here](https://dev.onedrive.com/README.htm#onedrive-api-root-resources).
