### ISSUE TITLE
Server/Deamon type authentication

### ISSUE THREAD

**Issue by brucewangkorea** [OneDrive/onedrive-sdk-csharp#179]
Hi,
I need to run my client in service/daemon mode, which means no user interaction is possible.
Here in Azure sample, you can use AppId and AppKey for this kind of application.
https://github.com/Azure-Samples/active-directory-dotnet-daemon

How can I use AppId and AppKey to pass the authorize process?

Best,

**Comment by cdmayer** [comment]
Actually, the SDK isn't responsible for handling authentication directly. That is handled by the `AuthenticationProvider`. The default implementation is [here](https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter).

Your scenario should definitely be achievable. You would need to make a new implementation of the `IAuthenticationProvider` [interface in Graph.Core](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/master/src/Microsoft.Graph.Core/Authentication/IAuthenticationProvider.cs). Here are your basic steps:

1. Create a new class, maybe `DaemonAuthenticationProvider : IAuthenticationProvider`
2. Add a method like `AuthenticateUserAsync` that goes through the OAuth flow (as shown in the sample to which you linked). You should end up with an auth token, which you should cache internally.
3. Implement `IAuthenticationProvider.AuthenticateRequestAsync`. This basically adds the cached auth token to the request. You can reference `MsaAuthenticationProvider.AuthenticateRequestAsync()` [for some ideas](https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter/blob/master/src/OneDrive.Sdk.Authentication.Common/MsaAuthenticationProvider.cs).
4. When you create your `OneDriveClient`, pass in an instantiation of your new auth provider.

That should be about it. If you end up implementing such a class, definitely submit a pull request to the Auth Adapter repository! That would be a great addition. If you have more questions, you can ask them here: https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter/issues
