### ISSUE TITLE
Cancellation support?

### ISSUE THREAD

**Issue by thomaslevesque** [OneDrive/onedrive-sdk-csharp#18]
Unless I'm missing something, there doesn't seem to be any way to cancel a request to the server. It would be better if all methods that call the server accepted a `CancellationToken`.

**Comment by ginach** [comment]
You're right that it's not currently supported, marking as enhancement for our backlog. Thanks for the feedback!

**Comment by aleks42** [comment]
Cancellation and IProgress.

**Comment by thomaslevesque** [comment]
Good point @aleks42, although it's only necessary for file transfers (the progress of other API calls doesn't really matter since they typically transfer small amount of data)

**Comment by ginach** [comment]
The request types the SDK can make fall into 3 categories:

1. Standard requests like GET /item that are relatively quick and return small amounts of data.
2. Heavier requests like upload and download that can be long-running and large.
3. Async method calls, like copy, that use the monitor API to check operation status.

For 1, unless the service is having issues, the call returns quickly enough that progress (and even cancellation) won't have much of a chance to kick in before the call returns. Adding this support is mostly useful in the service issue case.

For 2, progress and cancellation make much more sense. We're currently working on adding chunked upload support and extensions to use the Windows background upload and download APIs (on platforms where they're available) in the SDK itself. These will have progress and cancellation support from the get-go. In the existing simple upload and download cases, we're using System.Net.Http.HttpClient for the requests. This supports cancellation token and we should allow piping the token through. It doesn't support IProgress so we would have to [build something](http://stackoverflow.com/questions/21169573/how-to-implement-progress-reporting-for-portable-httpclient) in to handle reporting progress. With the upcoming upload and download changes progress will probably fall lower on the priority list.

For 3, both IProgress and cancellation token are already supported in the AsyncMonitor objects when calling `CompleteOperationAsync`.

**Comment by thomaslevesque** [comment]
> For 1, unless the service is having issues, the call returns quickly enough that progress (and even cancellation) won't have much of a chance to kick in before the call returns. Adding this support is mostly useful in the service issue case.

I'd argue that cancellation is still useful in this case. When the service is having issues, or the client has bad connectivity, it can be useful to let the user cancel an operation that is taking too long, rather than waiting for the timeout.

As for progress support in `HttpClient`, it's pretty easy to implement. I might send a PR for this if I can find the time ;)

**Comment by david-bakin** [comment]
@thomaslevesque is correct - bad connectivity will affect sync operations and cancellation should be supported. Also, easy timeouts! (Via an overload of GetAsync or some other mechanism on a request.)  So that each user doesn't have to reinvent the whell.

**Comment by ginach** [comment]
@david-bakin, correct, you can set the client timeout using that value. Unfortunately, HttpClient only allows setting the timeout before any requests are sent. If you need multiple timeouts you should have a separate HttpProvider instance for each.

I have a plan to support cancellation token but it's a breaking change in order to handle things properly. It's going to be a little while for the changes but the idea would be to support this with the next major version of the SDK.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
