### ISSUE TITLE
Special App Root folder problem

### ISSUE THREAD

**Issue by RussWalton** [OneDrive/onedrive-sdk-csharp#181]
From the C# SDK OneDrivePhotoBrowser example, what is the equivalent of:-

this.oneDriveClient.Drive.Items[id].Request().Expand(expandString)

for the special app folder?

this.oneDriveClient.Drive.Special.AppRoot.Items[id].Request().Expand(expandString)

is not possible and everything else I've tried gives me a graph error

Thanks,
Russ

**Comment by cdmayer** [comment]
Fixed in https://www.nuget.org/packages/Microsoft.OneDriveSDK/2.0.3
