### ISSUE TITLE
Exception when trying to create a share-link

### ISSUE THREAD

**Issue by miroppb** [OneDrive/onedrive-sdk-csharp#186]
When I try to create a "view" share link using:
`var create = await this.oneDriveClient.Drive.Items[uploadedItem.Id].CreateLink("view").Request().PostAsync();`

I get an exception:
`{"Could not load type 'Microsoft.Graph.BasePostMethodRequestBuilder`1' from assembly 'Microsoft.Graph.Core, Version=1.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.":"Microsoft.Graph.BasePostMethodRequestBuilder`1"}`

I have updated the SDK and Microsoft.Graph.Core to the latest versions, but I'm still getting the error.
Please help.

Also, on a side-note, how do I set a timeout for uploading? I can upload small files, but if I try to upload anything over ~50MB, it gives a timeout error

Thanks in advance

**Comment by cdmayer** [comment]
Please update to the newest version of the SDK, 2.0.4. It fixed the issue you are having (Graph changed the name of the class).

For larger files, I would recommend using the `ChunkedUploadProvider`. You can see it in action [here](https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/chunked-uploads.md).
