### ISSUE TITLE
How to get the thumbnail stream?

### ISSUE THREAD

**Issue by RussWalton** [OneDrive/onedrive-sdk-csharp#189]
Hi,

I'm trying to get an Item's Medium thumbnail into a stream.

I can get to the correct thumbnails but the content is always null.

How do I get to the content so I can return a stream?

![thumbnail](https://cloud.githubusercontent.com/assets/19670668/19830531/00242dae-9df2-11e6-9df4-cb3781fb1ff9.PNG)

Thanks,
Russ

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
