### ISSUE TITLE
CredentialsCache, System.Collections.Concurrent and Windows Phone 8.1?

### ISSUE THREAD

**Issue by jshansen** [OneDrive/onedrive-sdk-csharp#19]
I noticed references to using the SDK for Phone 8.1. In my attempt to mock up a basic prototype of this, I noticed the use of System.Collections.Concurrent, which isn't available in the Windows Phone 8.1 runtime as far as I can tell. Even a simple repro like var cache = new CredentialsCache(); within a WP8.1 project results in:

Additional information: Could not load file or assembly 'System.Collections.Concurrent, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Is this an issue in the implementation of the SDK or something that can be resolved within my project?

**Comment by ginach** [comment]
Could you provide more details on your project? Is it a WP 8.1 app, runtime component, etc? I'm not able to repro locally with a WP 8.1 app.

The System.Collections.Concurrent dependency is on [ConcurrentDictionary](https://msdn.microsoft.com/en-us/library/dd287191(v=vs.110).aspx), which is supported in .NET portable and WP 8.1 so the above error isn't expected.

**Comment by jshansen** [comment]
The project started out as an WP 8.0 project that was upgraded to target 8.1. I recreated the prototype project from scratch just now for WP8.1 and the problem isn't showing up anymore. Apparently the retargeting to 8.1 isn't fully accounting for the portable runtime. Thanks for spending time looking at this. I'll close the issue.
