### ISSUE TITLE
Incorrect exception when service is down

### ISSUE THREAD

**Issue by elegault** [OneDrive/onedrive-sdk-csharp#190]
I was just working on my app when suddenly I started getting exceptions for many GetAsync() calls that were working perfectly fine earlier.  The I noticed a message on the OneDrive web page: "OneDrive is read-only right now while we do some maintenance. We apologize for the inconvenience".  

The error is: "Code: unauthenticatedMessage: The caller is not authenticated." (HResult = -2146233088)

Perhaps error messages specific to service availability would be more appropriate?

(EDIT: I realized after I posted this that I wasn't checking ServiceException for a match on OneDriveErrorCode.ServiceNotAvailable, so perhaps this is already handled. My apologies if it is)

**Comment by cdmayer** [comment]
It does sound like this is an issue where the service was returning the wrong error code, but that wouldn't be an issue with the SDK. Next time you see something like this, even if it seems intermittent, can you post it on the [API Docs repo](https://github.com/OneDrive/onedrive-api-docs)? Thanks!
