### ISSUE TITLE
Does this SDK support 'Albums'??

### ISSUE THREAD

**Issue by assassin316** [OneDrive/onedrive-sdk-csharp#191]
Hi @cdmayer, 

I have a very quick question:

Does the OneDrive SDK support fetching a user's "Albums" (the new feature added this year) ?

[http://www.networkworld.com/article/2877034/onedrive-adds-albums-will-soon-add-automatic-photo-import-from-pc.html](http://www.networkworld.com/article/2877034/onedrive-adds-albums-will-soon-add-automatic-photo-import-from-pc.html)

![image](https://cloud.githubusercontent.com/assets/17514380/19905873/fb131988-a04e-11e6-9d89-c5cb2e7019b1.png)

Thanks for your time!!  :)

**Comment by cdmayer** [comment]
The API, and therefore the SDK, does not currently support Albums. That is definitely on our radar but I unfortunately can't make any comment on when it will be available. Thanks for asking!

**Comment by Aboisier** [comment]
Hey, just wanted to know if this have been implemented, or if it is still on your radar. I managed to retrieve an album by using its id, but can't find a way to retrieve the list of a user's albums ids.

Thank you!
Antoine
