### ISSUE TITLE
Consideration for OneDrive for Enterprise

### ISSUE THREAD

**Issue by lockelost** [OneDrive/onedrive-sdk-csharp#192]
Hi, I'm not sure already you are aware of this but, 
I think there's no possible way to list-up files for each users in the domain, with the AuthTOken of Global admin user account. I authenticate with Global Domain user (using AdalAuthenticationProvider.AuthenticateUserAsync()), and if I pass the  'baseurl' as just ' aad_target_url + "/_api/v2.0' it works but lists up the files of logged in user, the Global user. So if I change the  'baseurl'  to 
[aad_target_url + "/_api/v2.0/users/" + userid] then the Microsoft.Graph fails (The server returns Error). I will report this to OneDrive SDK.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
