### ISSUE TITLE
Open folder in OneDrive App from custom iOS App

### ISSUE THREAD

**Issue by GrischaJJ** [OneDrive/onedrive-sdk-csharp#195]
We would like to open a document folder of a SharePoint online document library (teamsite) in the iOS OneDrive App by pressing a button. The current user is following this teamsite. How would we do this?

**Comment by ahmedgharib** [comment]
Hey Crishca,

Thanks for the feedback! We are planning to add support for access to SharePoint content in the document provider extension in early 2017. That being said, we prioritize everything using UserVoice, so feel free to +1 this open request: [https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/7121558-allow-saving-to-shared-folders-in-ios-app](url)

Thanks Again!

-Ahmed

**Comment by GrischaJJ** [comment]
Hi Ahmed,

Thanks for your answer. Just want to make sure we are talking about the same thing. We don't want to access shared content over the OneDrive API. We just want to open the existing OneDrive iOS App from our iOS app. The OneDrive App gives us already access to the shared content that we need. We found no documentation about the URI of the iOS OneDrive App and how to directly jump into the folder we need.

BTW: Your link gives me a 404.

Thx, Grischa

**Comment by ahmedgharib** [comment]
Hi Grischa,


Are you opening the current OneDrive app using the Document Picker Provider? If not, how are you approaching pulling data from the App.


-Ahmed


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by GrischaJJ** [comment]
Hi Ahmed,

right now we are not opening the OneDrive app at all. We are planning to do so. 

Currently our app references files that are that are stored in a document library in SharePoint Online. We would like to open those file in the OneDrive App instead of opening it on the mobile browser.

I hoped I could open the file like this: oneDrive://PathToSharepointDocumentLibrary/filename

**Comment by Zebusch** [comment]
This would be a great thing to have, for sure!

**Comment by GrischaJJ** [comment]
https://msdn.microsoft.com/de-de/library/office/dn911482.aspx

OneDrive is missing unfortunately..

**Comment by daboxu** [comment]
closed on github as we have it tracked on UserVoice: https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/6540302-ios-8-storage-provider-extension-document-picker-s

**Comment by syates21** [comment]
The UserVoice link is not what was being asked for as near as I can tell.  He was asking for a URL scheme or some mechanism to launch and open specific content in the native OneDrive app.  This would be extremely useful, and it appears there is an ms-onedrive:// URL scheme.  I have not been able to find any documentation about what is supported with that though.  The closest UserVoice request I can find is [this one](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/10644789-add-support-for-ios-url-schemes-for-linking-to-the).
