### ISSUE TITLE
Item delta + Filter possible?

### ISSUE THREAD

**Issue by fridoo** [OneDrive/onedrive-sdk-csharp#198]
Is it possible to use filtering with item delta requests?

My code:
`Dim delta = client.Drive.Items.Item(fileMetadata.GetID).Delta(Nothing)`
`Dim currentfileRequest = delta.Request()`
`currentfileRequest.Filter(Uri.EscapeDataString("file ne null and deleted eq null"))`
`Dim currentItemPage = Await currentfileRequest.GetAsync()`

throws a ServiceExpection with the Error
> Message: The query specified in the URI is not valid. Query option 'Filter' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.

Does that mean that filtering delta results is not supported?

**Comment by cdmayer** [comment]
You are exactly right. Delta does not support filtering. You'll have to filter on the client side. I'll open a bug to deal with the documentation issue. Thank you for reporting!
