### ISSUE TITLE
How can I "page" my request?

### ISSUE THREAD

**Issue by assassin316** [OneDrive/onedrive-sdk-csharp#199]
I have the following code in which I want to get 20 child items at a time:

		var expandString = _client.AuthenticationProvider is MsaAuthenticationProvider
									? "thumbnails, children(expand=thumbnails)"
									: "thumbnails, children";

		var options = new List<Option>
		{
			new QueryOption("top", "20")
		};

		var item = await _client.Drive
						.Items[id]
						.Request(options)
						.Expand(expandString)
						.GetAsync(ct);

		// Get the "next" request for paging purposes (if it exists)
		_nextItemRequest = item.Children.NextPageRequest;

            var items = item.Children == null
				? new List<Item>()
				: item.Children.CurrentPage.Where(child => child.Photo != null);

But I receive the following error in Fiddler:

     The query specified in the URI is not valid. The requested resource is not a collection. Query options $filter, $orderby, $count, $skip, and $top can be applied only on collections.

What am I doing wrong?

**Comment by cdmayer** [comment]
The error message says that query options can only be applied to collections. You requested `Items[id]` which will return one item. Were you trying to get the children of that item? If so, try this request:

```csharp
var item = await _client.Drive
    .Items[id]
    .Children
    .Request(options)
    .Expand(expandString)
    .GetAsync(ct);
```

**Comment by assassin316** [comment]
Works like a charm!!   :)  Thanks.
