### ISSUE TITLE
Xamarin Android Project not buildable with onedrive sdk referenced

### ISSUE THREAD

**Issue by NPadrutt** [OneDrive/onedrive-sdk-csharp#20]
I use MVVM Cross in a project which includes a UWP, Android and IOS Project.
When add the onedrive sdk to the portable core I can no longer build the android project. The following error is thrown:

    Severity	Code	Description	Project	File	Line	Source
    Error	CS0246	The type or namespace name 'IOneDriveClient' could not be found (are you  missing a using directive or an assembly reference?)	MoneyManager.Core	     C:\Users\padruttn\Documents\GitHub\MoneyManager\Src\MoneyManager.Core\Manager\OneDriveManager.cs	31	Build

As far as I know xamarin should be supported by the c# sdk or did I get that wrong?

**Comment by ginach** [comment]
This was technically an issue with the old package. The portable library is actually only being built for .NET 4.5.1 + WP 8.1 + Win 8.1 but the package said .NET 4.5.1 + WP 8 + Win 8, allowing the Xamarin import. That said, I don't believe we're using any APIs that aren't also available for Xamarin so I'll look into retargeting the project and getting a new package out today.

**Comment by ginach** [comment]
You can view the PR here: https://github.com/OneDrive/onedrive-sdk-csharp/pull/22

**Comment by NPadrutt** [comment]
awesome. I will try it with the branch of the PR and give you a feedback. :)

**Comment by NPadrutt** [comment]
I tried the changes. When I build the source and reference it directly it works perfectly. Also if I create a own nuget package and install this. But the official nuget package seems to have the old nuspec and therefore I can't udpate to it.

**Comment by ginach** [comment]
We don't update the package until merge into master. I'll kick that off today and have someone ping the issue when the new package is up.

**Comment by NPadrutt** [comment]
ah alright. then it was by chance that I got an update yesterday evening =)

**Comment by aclev** [comment]
Hey @NPadrutt the nuget package should be up to date now!

**Comment by NPadrutt** [comment]
Just did the update. Build works as expected. Thanks for the fast help =)
