### ISSUE TITLE
how to log in when device is offline

### ISSUE THREAD

**Issue by deRightDirection** [OneDrive/onedrive-sdk-csharp#200]
assume the situation the app has already been connected to onedrive once. so the user information is in the vault.

next time the apps opens the phone is offline and i still want to access the files in the onedrive folder. how can i accomplish this? in the documentation i can't find anything about offline usage scenario's. why is there still a scope with the name wl_offlineaccess?

**Comment by flaviosuardi** [comment]
@MannusEtten did you find a way to access files offline (after online authetication)?

**Comment by deRightDirection** [comment]
no i did not, i gave up on the OneDrive stuff as much as possible, i switched to DropBox, better support for developers, better documentation and more stable API

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
