### ISSUE TITLE
Will the dependencies be updated?

### ISSUE THREAD

**Issue by assassin316** [OneDrive/onedrive-sdk-csharp#201]
I'm trying to install the UWP Community Services nuget package, but the OneDrive SDK is not allowing it because it's dependant on an older version of Active Directory. Will these dependencies be updated soon?

**_"Unable to find a version of 'Microsoft.IdentityModel.Clients.ActiveDirectory' that is compatible with 'Microsoft.OneDriveSDK.Authentication 1.0.6 constraint: Microsoft.IdentityModel.Clients.ActiveDirectory (> 2.22.0 && < 3.0.0)', 'Microsoft.Toolkit.Uwp.Services 1.2.0 constraint: Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.13.7)'.	"_**

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
