### ISSUE TITLE
Improper handling 302 Redirects when downloading file content?

### ISSUE THREAD

**Issue by gerarde** [OneDrive/onedrive-sdk-csharp#205]
I'm writing a C# web app (ASP.NET Core 1.0) which uses the OneDrive C# SDK to access a OneDrive for Business account.  It has code to upload/download files using the C# SDK.

The problem is that code to download a (which has been working for months) has mysteriously stopped working.

Notes: 
 * The Error property of the ServiceException is not useful - code is itemNotFound, with no further info. Screenshot below.
 * The same code works against other OneDrive accounts, just not this one.
 * Near identical code which uploads a file to the same location works just fine (i.e., a PUT to the same address works, it's just the GET that doesn't work).
 * Getting the item itself works fine (the code does this first) - it's just the GET for the /content that's returning an error.

I know this isn't an issue with the SDK, but have no idea where I can get help from Microsoft.  I do have an MSDN subscription, and am willing to use a support incident to figure this out, but nobody in the support center can seem to figure out how to route my call.  I've spent hours talking to SharePoint Online/OneDrive For Business support to no avail.

Any assistance would be much appreciated... thanks!

![image](https://cloud.githubusercontent.com/assets/813433/21022380/497bf7d0-bd31-11e6-9cf2-cf60792e7cf2.png)

**Comment by gerarde** [comment]
Turns out the issue may have been related to our custom IAuthenticationProvider and the fact that it was appending an Authorization header (with Bearer token) to SPO's `_layouts/15/download.aspx` endpoint which authenticates with a guestaccesstoken.

**Comment by frankguns** [comment]
Hi Gerarde,

Can you give some more details about how you solved this issue as I am facing exactly the same problem?

Thanks

**Comment by E3Solutions** [comment]
We are having the same issue. Do you have some example code of what you did to get it working?

Thanks

**Comment by gerarde** [comment]
What seems to be working for us providing an `HttpProvider` which specifies `AllowAutoRedirect=true` when initializing the `OneDriveClient`:

> return new OneDriveClient($"https://{Settings.OneDriveTenant}-my.sharepoint.com/_api/v2.0", new AuthenticationProvider(GetAccessToken), **new HttpProvider(new HttpClientHandler { AllowAutoRedirect = true }, true)**);

Our testing suggests it works with our particular uses of the library, but I'm not certain whether this causes any side effects.

**Comment by E3Solutions** [comment]
Works! Thank you, much appreciated!

**Comment by burnsy88** [comment]
Worked for us too!!  Here is the code we used:
 ```
  var adalAuthProvider = new AdalAuthenticationProvider(
                    this.AadClientId,
                    this.AadReturnUrl);

            this.oneDriveClient = new OneDriveClient(this.AadTargetUrl + "/_api/v2.0", adalAuthProvider, new HttpProvider(new HttpClientHandler { AllowAutoRedirect = true }, true));
            authTask = adalAuthProvider.AuthenticateUserAsync(this.AadTargetUrl);

            try
            {
                await authTask;
            }

```

**Comment by gerarde** [comment]
Reopening this since it looks like it's not just us -- it looks like the library (or the upstream Microsoft.Graph libs) is incompatible with a recent deployment of SPO.

Troubleshooting advice:
* Running the traffic through Fiddler (set proxy via `HttpClientHandler` `Proxy`/`UseProxy`) and toggling `AllowAutoRedirect` on/off demonstrates the incorrect flow of traffic.

Question for all: Does anyone know how to find a list of updates for O365/SPO/OneDrive and when they were deployed (i.e., release notes?)? MS Tech Support was completely unhelpful in helping to troubleshoot this problem.

**Comment by burnsy88** [comment]
Here's a link to the release notes for the OneDrive rollout they did on 12/7.

[https://support.office.com/en-us/article/New-OneDrive-sync-client-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0?ui=en-US&rs=en-US&ad=US]

**Comment by wethinjp** [comment]
The notes for Graph changes are available here: https://graph.microsoft.io/en-us/changelog#

**Comment by prakashguru** [comment]
My application is using 1.x sdk series and it is affected. I am not sure whether 2.x sdk also has the issues.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
