### ISSUE TITLE
Microsoft.Graph.ServiceException when trying to download files using the API

### ISSUE THREAD

**Issue by frankguns** [OneDrive/onedrive-sdk-csharp#206]
The following code

`var stream=await this.oneDriveClient.Drive.Items[itemid].Content.Request().GetAsync();`

is throwing the exception Microsoft.Graph.ServiceException.
The details of the exception is showing an ItemNotFound error code.

When checking the request by Fiddler, it seems the reponse of this call is a web page with the message: "Sorry something went wrong. Sorry you cannot access this document.".

This code was working for ages and now suddenly stopped working in the last few days.

I'm using the OneDriveSdk for downloading files from Sharepoint Online.

Any help would be highly appreciated.

**Comment by daboxu** [comment]
@frankguns can you still repro it? I believe it should be fixed.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
