### ISSUE TITLE
Add support for square thumbnails

### ISSUE THREAD

**Issue by tipa** [OneDrive/onedrive-sdk-csharp#207]
Currently, square thumbnails like "smallSquare" are not supported. Probably custom sized thumbnails could be somehow supported too...

Ref: https://dev.onedrive.com/items/thumbnails.htm#size-values
https://dev.onedrive.com/items/thumbnails.htm#custom-thumbnail-sizes

**Comment by daboxu** [comment]
hi @tipa , current the smallSquare thumbnail does return if you specify select it explicitly and there are some efforts needed:

build you request like
```csharp
    var size = "smallSquare";
    var expandString = string.Format("thumbnails(select={0})",size);
    var item = await this.oneDriveClient.Drive.Items[id].Request().Expand(expandString).GetAsync();

   // parse the thumbnail
   var thumbnailSet = item.Thumbnails.CurrentPage.FirstOrDefault(set => set.AdditionalData?[size] != null);
   if (thumbnailSet != null)
   {
       var serializer = new Serializer();
       var thumbnail = serializer.DeserializeObject<Thumbnail>(thumbnailSet.AdditionalData[size].ToString());
   }
```

this should also work if you want to select customized thumbnails, please let me know if it works.

**Comment by tipa** [comment]
I have come to a different solution via url parameters: `?width=80&height=80&cropmode=center`

**Comment by daboxu** [comment]
cool, good to know that.

**Comment by toby11** [comment]
@tipa how did you acheive passing in custom url parameters using the onedrive sdk?
