### ISSUE TITLE
"This file was generated by a tool and any changes will be overwritten"

### ISSUE THREAD

**Issue by adamsipos** [OneDrive/onedrive-sdk-csharp#209]
I understand it is possible to extend core functionality through the partial classes in the Extensions folders, however for some methods it'd be better to modify the core classes. For example, I'd like to add the Top variable to IItemRequestBuilder.Delta(). Could you please let me know how these classes are generated? Thanks!

**Comment by daboxu** [comment]
hi @adamsipos , the file is generated by a tool and template we maintained internally so if you are requesting for missing properties on the item, feel free to open an issue for it. And for your delta case, I believe we have already support it. You can build a request like:

```csharp
var result =
                    await this.oneDriveClient.Drive.Items[this.CurrentFolder.Id].Delta(null).Request().Top(2).GetAsync();
```

to get two items back. The interface is [here](https://github.com/OneDrive/onedrive-sdk-csharp/blob/38599a4988bb8a05c23493537a3ebd87b9c33b30/src/OneDriveSdk/Requests/Generated/IItemDeltaRequest.cs#L54).

**Comment by Srusti-Thakkar** [comment]
@daboxu  Can you tell me How to work with Delta Request for Personal Account in c#? If you have any example then post it please.

**Comment by daboxu** [comment]
@Srusti-Thakkar just in about comment:
```csharp
var result = await this.oneDriveClient.Drive.Items[this.CurrentFolder.Id].Delta(null).Request().GetAsync();
```
