### ISSUE TITLE
OneDrive SDK support for Graph service or daemon? 

### ISSUE THREAD

**Issue by jaycdave88** [OneDrive/onedrive-sdk-csharp#217]
Question 1. 
Does the OneDrive SDK use Microsoft Graph under the cover? 

Question 2. 
If so is it possible to bypass the OAuth authentication by using Microsoft Graph in a service? [Microsoft Docs](https://graph.microsoft.io/en-us/docs/authorization/app_only)?

**Comment by daboxu** [comment]
hi @jaycdave88 , if you want to integrate with Microsoft Graph service, I would suggest you use the [Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-dotnet) as well.
