### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by MichaelStgt** [OneDrive/onedrive-sdk-csharp#218]
This is really confusing regarding the authentication process. When I register my app as described in https://dev.onedrive.com/auth/readme.htm, wouldnt then my app will request MY OneDrive Storage?? I want to let my users save database files on THEIR OneDrive Account, not in my One? Or do I Get something wrong here?
The sample in the UWP Community Toolkit does not request any ID from me, and when I run the App out of Visual Studio, I can not access my OneDrive Account. If i install the app from the store, there is no problem.

Kind Regards,
Michael

**Comment by daboxu** [comment]
hi @MichaelStgt , based on your story, probably you want to create an application which works which our C# SDK will represents as your APP to let OneDrive User allow your app to access their OneDrive storage. Using OneDrive for Consumer account and C# Platform for example, you need to go to [App Registration Page](https://apps.dev.microsoft.com) to create an app and pass in your app's ID to MSAAuthAdapter to C# SDK which will build the HTTP requests for you to talk to OneDrive API. More details is in the [documentation for MSAAuthAdapter](https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter) for OAuth for OneDrive Consumer account at C# Platform.

**Comment by daboxu** [comment]
close for now, feel free to reopen it if you have any questions.
