### ISSUE TITLE
Support for .netStandard

### ISSUE THREAD

**Issue by abdulrehmangill** [OneDrive/onedrive-sdk-csharp#224]
Now that msgraph targets .netstandard, when can we expect onedrive-sdk for C# to start targeting .netstandard ?

**Comment by daboxu** [comment]
hi @abdulrehmangill as our goal is to merge with Microsoft Graph SDK, you would better have a look at their [page](https://github.com/microsoftgraph/msgraph-sdk-dotnet). They have related PR for .netStandard support https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/84.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
