### ISSUE TITLE
How can use files from shared folders embedded in your OneDrive using OneDrive SDK c#?

### ISSUE THREAD

**Issue by diego2265** [OneDrive/onedrive-sdk-csharp#226]
Seems that you can not download / upload files from shared folders embedded in your OneDrive using OneDrive SDK c #.

Steps to simulate the behavior:

1. User "A"  shares a Onedrive folder named "Shared01" with user "B" with "modify" permission;
2. User "B" incorporates "Shared01" into its own Onedrive: the folder "Shared01" appears in the root of "B";
3. Using the c# SDK (OneDriveApiBrowser.sln) and the user "B" credentials, the folder "Shared01" is correctly visible on the root, but:

- If you navigate inside the folder "Shared01"  the files stored in the folder are not displayed;
- You can not upload/download or modify the files inside in the folder.

Also, if you try using the {item-id} of the files contained in "Shared01" through the request: 

GET /drive/items/{item-id}/content

You get the following error:
"{Code: itemNotFoundThrow site: 29a3.1155Message: Item does not exist}"

In the past, that request worked.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
