### ISSUE TITLE
Q: No manual sign in to one drive for business

### ISSUE THREAD

**Issue by Nimeena** [OneDrive/onedrive-sdk-csharp#227]
Hello, I am trying to integrate one drive for business to our web application. I red in many places that one drive always need manual sign in (browser sign in) to access the docs . Is it possible for my application to access the docs in google drive and let the user view/edit the docs without any manual sign in? 

So something like application has a one drive for business account , that it can let its users view/edit

Thanks!

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
