### ISSUE TITLE
File copy doesn't work when the destination path is in the same folder as the original file.

### ISSUE THREAD

**Issue by gandhiz** [OneDrive/onedrive-sdk-csharp#228]
Hi,

The following code doesn't work when toParentFolderId is the same folder id as the original file:

var status = await client.ItemWithPath(fromPath).Copy(toFileName, new ItemReference {Id = toParentFolderId}).Request().PostAsync();
var item = await status.PollForOperationCompletionAsync(null, CancellationToken.None);

The error I get is:

Microsoft.Graph.ServiceException: Code: generalException
Message: Unexpected exception returned from the service.

This error appears after I updated Microsoft.OneDriveSDK to the latest version.

Do you have the same issue?

Thanks.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
