### ISSUE TITLE
graph.core issue

### ISSUE THREAD

**Issue by RickySan65** [OneDrive/onedrive-sdk-csharp#233]
Hi there,

I have the latest sdk installed, graphcore has been updated to 1.5.x (for reason it insisted on that), the odd thing is that on some machines it still wants to see 1.3.1 instead of the 1.5.x dll.. i noticed the sdk package still depends on 1.3.  so not sure if this is a bug or not, but on my dev machines it works, if i move it to another machine, the graphcore error comes up

**Comment by IlyaBezus** [comment]
Same here - not working, if I have OneDriveSDK along with Graph.Core 1.3.1+

**Comment by RickySan65** [comment]
19 days since opening issue, not very responsive...

**Comment by oatsoda** [comment]
Also have this problem. Actively stopping me from upgrading other dependencies in my project.

It seems like this OneDrive SDK isn't being maintained any more. Is this still the recommended client?

**Comment by oatsoda** [comment]
I guess this is the answer...

https://github.com/OneDrive/onedrive-sdk-csharp/issues/224#issuecomment-288259165

> our goal is to merge with Microsoft Graph SDK, you would better have a look at their page.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
