### ISSUE TITLE
Examples for using @microsoft.graph.conflictBehavior in the sdk

### ISSUE THREAD

**Issue by themasterchiefdev** [OneDrive/onedrive-sdk-csharp#235]
The [onedrive API documentation](https://dev.onedrive.com/items/upload_put.htm) specifies that @microsoft.graph.conflictBehavior can be used as the optional query string parameters but the examples listed under the docs does not specify its usage.  

Can @microsoft.graph.conflictBehavior usage be included in the examples in the [docs](https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/items.md) please?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
