### ISSUE TITLE
ItemWithPath can't handle "invalid characters"

### ISSUE THREAD

**Issue by tvandijck** [OneDrive/onedrive-sdk-csharp#236]
in the example [here](https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/items.md#2-by-path)
```
.ItemWithPath(parentItem.ParentReference.Path + "/" + parentItem.Name + "/relative/path")
```

should be fixed to:
```
.ItemWithPath(parentItem.ParentReference.Path + "/" + Uri.EscapeDataString(parentItem.Name + "/relative/path"))
```

or, the ItemWithPath API itself should handle the right escaping.

Without the escaping I was getting exceptions on invalid characters:
```
Code: invalidRequest
Throw site: 5669.22a3
Message: Path (/LiveFolders/Pictures Shanon/2004-01-01, Crossfit ) contains invalid trailing character.

Inner error
Code: nameContainsInvalidCharacters
```

I tried:
- HttpUtility.UrlEncode
- HttpUtility.UrlEncodeUnicode
- HttpUtility.UrlPathEncode
- Uri.EscapeDataString

but it appears only the Uri.EscapeDataString covers all cases.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
