### ISSUE TITLE
The remote certificate is invalid according to the validation procedure error when using chunked upload

### ISSUE THREAD

**Issue by themasterchiefdev** [OneDrive/onedrive-sdk-csharp#237]
Hi,
I'm trying to upload document using the chucked upload provider. The upload is done from behind a firewall and I get an error saying "The remote certificate is invalid according to the validation procedure"
Can you provide the list of URLs which need to be white listed on our firewall so that I can use the functionality please? 
I have already got  https://api.onedrive.com/rup added to the white list.

Thanks

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
