### ISSUE TITLE
Upload large file raise Unsupported segment type 

### ISSUE THREAD

**Issue by m4ss1m0g** [OneDrive/onedrive-sdk-csharp#239]
I used the code for [Chunked Upload](https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/chunked-uploads.md) but with no luck,

I've tried:

```
var uploadPath= "MyFile.exe";
var session = await oneDriveClient
                    .Drive
                    .Root
                    .ItemWithPath(uploadPath)
                    .CreateSession()
                    .Request()
                    .PostAsync();
```

Also I tried

```
var session = await oneDriveClient
                     .ItemWithPath(uploadPath)
                     .CreateSession()
                     .Request()
                     .PostAsync();
```

But every time I got and Error

> Unsupported segment type. ODataQuery: users/xxxxxx@yyyyy.onmicrosoft.com/drive/root/zzzzz/oneDrive.createSession

The "classic" upload work correctly.

I use Bearer Token with custom **IAuthenticationProvider** where the token came from App auth with delegate permissions

**Comment by oatsoda** [comment]
It looks like this only affects OneDrive for Business - it works fine for Consumer OneDrive.
