### ISSUE TITLE
Folder creation

### ISSUE THREAD

**Issue by Joker8991** [OneDrive/onedrive-sdk-csharp#24]
Hello! How can I create a folder in root via Onedrive SDK in uwp app?
I tried in different ways but I did not succeed.
Thank you

**Comment by ginach** [comment]
Here's how you can create a folder:
```csharp
    var folderToCreate = new Item { Name = folderName, Folder = new Folder() };
    var newFolder = await client.Drive.Items[parentId].Children.Request().AddAsync(folderToCreate);
```

**Comment by ginach** [comment]
Closing the issue, please reopen if I didn't address your question.
