### ISSUE TITLE
Warning	NU1608	Detected package version outside of dependency constraint:

### ISSUE THREAD

**Issue by zipswich** [OneDrive/onedrive-sdk-csharp#242]
I get the following warning when building a UWP app:

> Warning	NU1608	Detected package version outside of dependency constraint: Microsoft.OneDriveSDK.Authentication 1.0.10 requires Microsoft.IdentityModel.Clients.ActiveDirectory (> 2.22.0 && < 3.0.0) but version Microsoft.IdentityModel.Clients.ActiveDirectory 3.19.1 was resolved.	

			

I am wondering if it is relevant here. It is not a big deal because the app appears to run fine. However, it has mysterious crashes occasionally. I am examining all possible factors now.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
