### ISSUE TITLE
Warning NU1602

### ISSUE THREAD

**Issue by queequac** [OneDrive/onedrive-sdk-csharp#245]
`NU1602: Microsoft.OneDriveSDK.Authentication 1.0.10 does not provide an inclusive lower bound for dependency Microsoft.IdentityModel.Clients.ActiveDirectory (> 2.22.0 && < 3.0.0). An approximate best match of Microsoft.IdentityModel.Clients.ActiveDirectory 2.22.302111727 was resolved.
`

This is not a big issue, but would be great if you could correct the lower bounds - the current version of the OneDriveSDK shows always above warning during build.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
