### ISSUE TITLE
UWP XBox One Can't Interact with Sign In UI

### ISSUE THREAD

**Issue by RexfelisLOC** [OneDrive/onedrive-sdk-csharp#246]
Using the following code to sign in which works fine in an UWP app on Desktop, but on Xbox One, the cursor disappears and there is no way to interact with the Yes button to grant permissions.  Is there something else I need to do?

`var scopes = new[] { "wl.emails","wl.signin"};
_oneDriveClient = new OnlineIdAuthenticationProvider(scopes);

await _oneDriveClient.AuthenticateUserAsync();`

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
