### ISSUE TITLE
OneDriveSdk assembly strong name issue

### ISSUE THREAD

**Issue by denisbednov** [OneDrive/onedrive-sdk-csharp#25]
An unhandled exception of type 'System.IO.FileLoadException' occurred in OneDriveSdkTest.exe

Additional information: could Not load file or Assembly "OneDriveSdk, Version=1.1.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" or one of its dependencies. Failure to verify that strong name. (Exception from HRESULT: 0x8013141A)

Windows 7
.NET 4.5.2
Visual Studio 2013

**Comment by ginach** [comment]
Thanks for reporting this, it looks like the current package assemblies are not correctly signed. We'll get a new package up today.

**Comment by ginach** [comment]
This should be fixed with package version 1.1.6. Please reopen this issue if you're still hitting issues.
