### ISSUE TITLE
Request() method throws exception

### ISSUE THREAD

**Issue by marcnet80** [OneDrive/onedrive-sdk-csharp#252]
The code samples didn't work, after packages updates (_Newtonsoft.Json_ to 12.0.0.0 and _Microsoft.Graph.Core_ to 1.18.0.0):

```
var item = await oneDriveClient
                     .Items[itemId]
                     .Request()
                     .GetAsync();
					 
var item = await oneDriveClient
                     .Drive
                     .Root
                     .ItemWithPath("path/to/file/txt")
                     .Request()
                     .GetAsync();
```
Microsoft.OneDriveSDK Version : 2.0.7
Exception message: 
<pre>
Method not found: 'Void Microsoft.Graph.BaseRequest.set_SdkVersionHeaderPrefix(System.String)'.
</pre>

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
