### ISSUE TITLE
System.MissingMethodException set_SdkVersionHeaderPrefix

### ISSUE THREAD

**Issue by ForerunnerG34** [OneDrive/onedrive-sdk-csharp#253]
I'm using **Microsoft.Identity** to sign in into MS Graph and obtain an object of **IPublicClientApplication**.  Scopes: "**Files.ReadWrite.AppFolder**", "Files.Read.All"

Then I'm trying to read any folder from OneDrive, for example the AppFolder:

 **IntegratedWindowsAuthenticationProvider authenticationProvider = new IntegratedWindowsAuthenticationProvider(PublicClientApp, scopes);
            var oneDriveClient = new OneDriveClient(authenticationProvider);
            var rootItem = await oneDriveClient.Drive.Special.AppRoot.Request().GetAsync(); // throws exception**

And it throws this exception:

**System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Microsoft.Graph.BaseRequest.set_SdkVersionHeaderPrefix(System.String)'.
  Source=Microsoft.OneDrive.Sdk
  StackTrace:
   at Microsoft.OneDrive.Sdk.ItemRequest..ctor(String requestUrl, IBaseClient client, IEnumerable`1 options)
   at Microsoft.OneDrive.Sdk.ItemRequestBuilder.Request(IEnumerable`1 options)
   at Microsoft.OneDrive.Sdk.ItemRequestBuilder.Request()**

**Comment by Thomi7** [comment]
Same for me

**Comment by YuraGoots** [comment]
I've got the same error when trying to up version of Microsoft.Graph and Microsoft.Graph.Core libraries.
It looks like Microsoft.OneDriveSDK works only with Microsoft.Graph/Microsoft.Graph.Core 1.12.0.

**Comment by YuraGoots** [comment]
I've investigated why this happened.
That's because new implementation of Microsoft.Graph.BaseRequest does not contain this property:

        // Summary:
        //     Gets or sets the telemetry header prefix for requests.
        protected string SdkVersionHeaderPrefix
        {
            get;
            set;
        }

And in Microsoft.OneDrive.Sdk.ItemRequest ctor we can see this code:

`
this.SdkVersionHeaderPrefix = "onedrive";
`

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
