### ISSUE TITLE
How to use net core to call onedrive?

### ISSUE THREAD

**Issue by bbhxwl** [OneDrive/onedrive-sdk-csharp#254]
How to use net core to call onedrive?

**Comment by Mogikan** [comment]
Since this repo is dead I maintain this project a bit. In case someone need .net standard support (.net core, xamarin and .net 5): https://github.com/Mogikan/onedrive-sdk-csharp
I maintain it since I need it in to use in my project.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
