### ISSUE TITLE
How to log in with account other than default?

### ISSUE THREAD

**Issue by yosefbernal** [OneDrive/onedrive-sdk-csharp#255]
I have followed your introduction and managed to successfully authenticate, read, and write files in my personal account. The problem is I don't see a way to log in with a different account. The dialog assumes I want to use my default Windows account whereas I'd like to use my work account. You might say: "well .. just log in with your work account!". Well, that would be a problem since, as you know, all your account details get synched across windows (email, office, OneNote, OneDrive, etc). I have looked around the documentation but I haven't found anything alluding to this.

Any clues?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
