### ISSUE TITLE
OneDrive URI Scheme

### ISSUE THREAD

**Issue by SadeghPM** [OneDrive/onedrive-sdk-csharp#256]
Hi,

is there any URI scheme for the OneDrive app? 

For instance, Microsoft Office has had its own URI scheme since its 2010 version [[link](https://learn.microsoft.com/en-us/office/client-developer/office-uri-schemes)]

**Comment by mikevasiloff** [comment]
@SadeghPM while not "specific" documentation like the one for Office URI Schemes, I've found these which detail some of the **OneDrive** URI scheme options:
- https://learn.microsoft.com/en-us/sharepoint/deploy-on-windows
- https://techcommunity.microsoft.com/t5/sharepoint-developer/rest-get-onedrive-sync-link/m-p/228797

I too am looking for "official" documentation on the OneDrive URI scheme.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
