### ISSUE TITLE
Automatic handling of backoff?

### ISSUE THREAD

**Issue by mybluedog** [OneDrive/onedrive-sdk-csharp#26]
Does the API automatically handle backoff in case the OneDrive service feels it's being hit too hard?  If not, is there any plan to?

**Comment by rgregg** [comment]
The service will send HTTP 429 and/or HTTP 503 responses when an application has exceeded the API call limits or the service needs an application to back off. In general well designed apps that leverage the features of the API (view.delta, webhooks, ?expand, etc) don't run into these throttles.

**Comment by ginach** [comment]
Closing the issue. Please reopen if your question has not been addressed.
