### ISSUE TITLE
'Sign in with different User' option

### ISSUE THREAD

**Issue by Miittcchhzz** [OneDrive/onedrive-sdk-csharp#32]
Hello world,

Have been using the C# Winforms SDK to create an Uploader and have found issue with cached credentials. When I log in with user X, it seems IE will cache that in some live login cookies so each subsequent run of the application will load user X and only has options on consent screen for "Yes or No" to allow user X. Id like the option at this point to 'select a different user', said link could perhaps perform the logout operation for the cached user.

Many thanks in advance!

Mitch.

**Comment by ginach** [comment]
Thanks for the feedback, Mitch! I agree, this would be a nice improvement. Marking as enhancement to track.

**Comment by ginach** [comment]
This is a service ask for login. After reaching out to the accounts team this is a won't fix.
