### ISSUE TITLE
Trying to access empty Shared With Me throws

### ISSUE THREAD

**Issue by mybluedog** [OneDrive/onedrive-sdk-csharp#33]
If there is nothing Shared With Me and I try to access the Shared With Me 'folder', I get an exception saying the item wasn't found.  It would be more convenient if this function returned an empty Enumeration instead of throwing.

SDK version = 1.1.15
C# console app on Win 10-64

To reproduce:
```c#
// Use a 'home consumer' OneDrive account that has nothing shared with it.
OD.IDriveSharedWithMeRequestBuilder swmRequestBuilder = OneDrive.client.Drive.SharedWithMe();
OD.IDriveSharedWithMeCollectionPage result = swmRequestBuilder.Request().GetAsync().Result; // throws
```

**Comment by mybluedog** [comment]
This might apply to ordinary folders that are empty too.

**Comment by mybluedog** [comment]
It also seems that this only applies to accounts that have never had anything shared with them before.  If you share something with an account and then 'unshare' it, the exception no longer occurs.

**Comment by ginach** [comment]
Thanks for reporting this issue. view.sharedWithMe is an undocumented API that shouldn't be in the SDK until it's ready for the public. We'll be removing it from all of the SDKs until then.
