### ISSUE TITLE
Can't authenticate, UserCancel always returned.... 

### ISSUE THREAD

**Issue by chabiss** [OneDrive/onedrive-sdk-csharp#34]
I've been following the instructions from https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/auth.md

I do have my app registered to the store with his proper Client id.  I've been trying those three examples: 

Attempt #1 
var client = OneDriveClientExtensions.GetUniversalClient(this.oneDriveScopes) as OneDriveClient;

Attempt #2
            IWebAuthenticationUi webAuthenticationUi = new WebAuthenticationBrokerWebAuthenticationUi();             
             var client = OneDriveClient.GetMicrosoftAccountClient(
                                        appId: ClientId,
                                        returnUrl: "https://login.live.com/oauth20_desktop.srf",
                                        scopes: oneDriveScopes ,
                                        clientSecret: ClientSecret,
                                        credentialCache: null,
                                        httpProvider: null,
                                        serviceInfoProvider: new ServiceInfoProvider(webAuthenticationUi));
Atempt #3
            var client = await OneDriveClientExtensions.GetAuthenticatedClientUsingWebAuthenticationBroker(appId: ClientId, scopes: oneDriveScopes);
            try
            {
                await client.AuthenticateAsync();
            }

All those attempts fails at : the call to 
result = await this.AuthenticateAsync(requestUri, callbackUri, WebAuthenticationOptions.None);

inside 
C:\development\onedrive-sdk-csharp-master\src\OneDriveSdk.WinStore\Authentication\WebAuthenticationBrokerWebAuthenticationUi.cs#Line 61

The response status is always ResponseStatus : UserCancel. 

What gives?

**Comment by ginach** [comment]
Issue resolved offline. Issue was in trying to authenticate the client too early in the App (within the App constructor).
