### ISSUE TITLE
Timeline for OneDrive for Business C# API

### ISSUE THREAD

**Issue by mybluedog** [OneDrive/onedrive-sdk-csharp#35]
When is the anticipated release date for the OneDrive for Business Windows C# API?

**Comment by ginach** [comment]
We released it at Connect() last month. Other than the differences documented in the [business endpoint release notes](https://dev.onedrive.com/odb-preview/release-notes.htm) the 2 endpoints behave the same way. For using the SDK against the business endpoint take a look at the Azure Active Directory (AAD) authentication section in the [auth documentation for the SDK](https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/auth.md). Authentication is the only way in which the SDK calling each endpoint differs.

One caveat is that app-only authentication is not currently enabled with the SDK. Issue #36 tracks adding the support.
