### ISSUE TITLE
App-only, client secret, refresh token authentication support in AAD

### ISSUE THREAD

**Issue by ginach** [OneDrive/onedrive-sdk-csharp#36]
Enable client credential (app-only), client secret web flow, and refresh token authentication in AAD.

**Comment by mybluedog** [comment]
Sorry to hassle you @ginach, but is this planned for the near future?

**Comment by ginach** [comment]
It is, I'll be working on it after the holidays.

**Comment by mybluedog** [comment]
That's great.

I've been working on the web sign-in side and I want to check that I have retrieved the right data that your new function is likely to take.

I have...
client ID
redirect URI
refresh token
service resource ID
service endpoint URL

Notes - 
1. There is no client secret in Azure for this app.
2. I'm not sure if I need to get a refresh token for the MyFiles endpoint, or if I can use any old refresh token.

**Comment by dlfu** [comment]
Hi, 
Just wanted to check if there is any updates on the secret flow? 
Thanks
Delong

**Comment by narsenault** [comment]
@ginach Is it possible to get an approximate time frame when this will be completed?

**Comment by ginach** [comment]
My goal is to have code changes done by Monday at which point I can send out a PR. If you want to look at the changes as they are right now here's my working branch: https://github.com/ginach/onedrive-sdk-csharp/tree/businessAuthFixes

**Comment by dlfu** [comment]
Awesome!
im using the sdk through nuget package, would it also be updated sometime next week then?

**Comment by ginach** [comment]
Correct. We'll push a new package once changes are merged into master.

**Comment by ginach** [comment]
Code changes are there but finishing up tests. PR will be out once the tests are ready.

**Comment by mybluedog** [comment]
Hi @ginach.  Is Refresh token auth now supported for Business?

**Comment by ginach** [comment]
No, my current PR addresses app-only and web client authentication but not refresh token. I'm finishing up responding to the PR feedback I've received offline and then I can work on sending out one for refresh token authentication.

**Comment by dlfu** [comment]
any updates?

**Comment by nsouren** [comment]
Do you have any news on refresh token auth support for Business?

**Comment by ginach** [comment]
I've just finished a bunch of manual testing and fixes for PR #72 if folks would take a look. If I don't hear anything I'm going to merge tomorrow.

**Comment by ginach** [comment]
Fixed in latest package push.
