### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by pbaldo** [OneDrive/onedrive-sdk-csharp#40]
The only error message returned is "Exception of type 'Microsoft.OneDrive.Sdk.OneDriveException' was thrown.". No detail is given as per why the request raised this exception which makes it hard to handle the exceptions on the client side. The exceptions raised need more details.

**Comment by ginach** [comment]
OneDriveException has an Error property with a code and a message. Also, if it is thrown as the result of another Exception, that Exception will be the InnerException of the OneDriveException. You'll want to key off these values to figure out the exception details.

OneDriveException also has a method IsMatch(string errorCode) to help check if an exception is the specified error code. For example, you can see if the exception is "itemNotFound" you can do so like this:

```csharp
oneDriveException.IsMatch(OneDriveErrorCode.ItemNotFound.ToString())
```

**Comment by pbaldo** [comment]
Thanks for the response, works great!
