### ISSUE TITLE
Accessing another user's OneDrive for business drive

### ISSUE THREAD

**Issue by miker2069** [OneDrive/onedrive-sdk-csharp#42]
Is it possible with the SDK to access another user's OneDrive for business drive with an admin account?

**Comment by nsouren** [comment]
Any news on this question?

**Comment by ginach** [comment]
You can access another drive using client.drives[driveId]. As long as the authenticated caller has access to the drive ID then the call should succeed.

**Comment by elegault** [comment]
Is DriveID the user name?  I've got a user with a OneDrive URL like this: https://mydomain-my.sharepoint.com/personal/usera_mydomain_onmicrosoft_com/Documents.  And code like this (simplified for brevity), but it throws an exception:

`        private async Task LoadUserDriveTest()
        {
            Item folder;

            var expandValue = "thumbnails,children";
            
            folder = await oneDriveClient.Drives[$"usera_mydomain_onmicrosoft_com"].Root.Request().Expand(expandValue).GetAsync();
            //Code: invalidRequest
            //Message: The provided drive id appears to be malformed, or does not represent a valid drive.
        }`

**Comment by cdmayer** [comment]
The DriveId is a string that uniquely identifies the drive. It is not an account name or user name. It is assigned by the system.

The code you provided is not valid. `Drives[{driveId}]` expects a DriveId, but what you provided is certainly not a valid DriveId. However, you can instead use the extension `OneDriveClient.Drive` which is a shortcut to basically say "the drive of the signed-in user." If you want to access a drive other than the signed-in user, you need to first know the target user's DriveId. You can find out a user's DriveId using this simple call:

```csharp
var drive = await oneDriveClient.Drive.Request().GetAsync();
var driveId = drive.Id;
```

**Comment by elegault** [comment]
Actually, @rgregg guided me to use the SMTP address of the user as the drive ID - and it works!  e.g. folder = await oneDriveClient.Drives["user@domain.com"].Root.Request().Expand(expandValue).GetAsync();

**Comment by cdmayer** [comment]
I apologize for misrepresenting the API. Even I did not know that was possible! I updated the comment above.

**Comment by elegault** [comment]
I've been testing this approach heavily over the weekend, and it appears flakey or some user's drives just cannot be accessed for some reason (the permissions are good).  I've been seeing this error: 

Code: invalidRequest Message: The provided drive id appears to be malformed, or does not represent a valid drive. 
HResult: -2146233088

This has happened consistently for a certain set of users, and for two users it failed but then subsequently worked with a second or third attempt.

I will try your approach with the drive ID to see if it works - would this be the call: oneDriveClient.Drives["user@domain.com"].Request().GetAsync()

**Comment by elegault** [comment]
I tried using the Drive ID approach - it only worked for one of the users where it failed by using their email address.  I will see if I can get the AAD object ID for the users where it is failing.  Otherwise any guidance would be super appreciated! This is a super high-priority project and I'm going to look bad if I can't process a high percentage of users. :-(  /cc @rgregg

**Comment by rgregg** [comment]
Hey Eric: Can you reach out to me directly? (rgregg -at- microsoft.com). 

For failed calls, if you can send me the request ID, the date/time the request was made, and the tenant you were using, I can look up the details and sort out why you're getting that error and if we have a bug hiding or something else.

Also, just to make sure, you need to use the UPN, not a user's email address (most of the time they're the same, but not always).

**Comment by elegault** [comment]
Me again, talking into the wind lol!  Turns out it was a permissions issue - the admin account was only granted the Application Impersonation Role.  This apparently adds the account to the user's Site Collection Admins, but the issues went away when he added the admin account manually.

**Comment by rgregg** [comment]
That's good to hear. Sounds like we could use a better error state though for that scenario.

**Comment by elegault** [comment]
BTW, my apologies for totally missing your reply.  I've been overcoding and need some sleep!  Thanks Ryan

**Comment by jaycdave88** [comment]
Is there a way to grant permissions to manage a custodian user's OneDrive through the SDK? I created a SO on the question as well which has more context. 

http://stackoverflow.com/questions/42012975/access-files-for-custodian-account-from-admin-account-onedrive-sdk-csharp-is-th
