### ISSUE TITLE
Request to support an OData $skip option to support virtual data lists on clients

### ISSUE THREAD

**Issue by ericleigh007** [OneDrive/onedrive-sdk-csharp#43]
Though the current server paging capability can support an incremental loading capability, this doesn't support at all the case of user quickly scrolling through their photos or data in a virtual list, because scrolling can be done so quickly that any incremental loading queue can get saturated. 

Random access data virtualization is what is required to support the quick scrolling scenario. Unfortunately, it looks as if the SDK and the OneDrive API don't support the OData query options (namely $skip) which would enable that.

Hopefully $skip is in the near range plan, so that we'll be able to create awesome third party apps that use the OneDrive API.
The concepts I'm describing can be found here:
https://msdn.microsoft.com/en-us/library/windows/apps/mt574120.aspx

To illustrate, let's say that a list or grid is used to show picture thumbnails.  We start with a query to get the camera roll by date descending, but we only get just a few of the thousands of pictures' metadata with the first call.  In fact, to remain responsive, we may want the call to get even fewer than 100 items.
```
https://api.onedrive.com/v1.0/drives('me')/items('cameraroll_id')/children?$top=100&$orderby=lastModifiedDateTime%20desc
```

Now the user scrolls very quickly to item 200, but we're still loading the previous items into the control.  This might be reported to the app by the `IItemsRangeInfo` interface for a list and overriding the `RangesChanged` method..

What we need is this:
```
https://api.onedrive.com/v1.0/drives('me')/items('cameraroll_id')/children?$top=100&$orderby=lastModifiedDateTime%20desc&skip=200
```

If there is a way to enable this scenario, please let me know.
-THANKS
-e

**Comment by rgregg** [comment]
Hi Eric -- this is a scenario that's top of mind for us, but we don't have a solution yet. Please consider adding this suggestion to our [UserVoice page](https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer).

**Comment by ericleigh007** [comment]
Done: https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/11357844-please-add-the-odata-skip-query-option-to-a
Developers: please vote this up.  Thx

**Comment by ericleigh007** [comment]
Hi @rgregg, I do realize that supporting what amounts to non-volatile stored data for each OneDrive API session can be tricky, I would make the following suggestions:
o I would first follow the OData guidelines here, but since OneDrive is a minimal ODrive implementation,
o I would remove any temp data representing the query state when the session logs out
o I would support a few, but some small limited number of queries simultaneously (I would expect that a small number of concurrent queries would be used by some highly performant apps).
o You might support some way to "clear" all of the context.

-thanks
-e

**Comment by rgregg** [comment]
The trickiness with $skip is that it requires us to calculate and land you in an exact place in the dataset which assumes that you can calculate and know where you want to be. This is expensive from a data retrieval view because we have to page through the records you want to skip over to get the records you're looking for. We've been kicking around how we can solve this scenario in another way that wouldn't require the same precision but would enable the scenario of jumping around within a list.

We've been thinking through the scenarios and think it may be useful to be able to skip to a location based on some aspect of the data you expect to find _other_ than position index, like "items that start with F" or "items from 2014", etc.

It'd be interesting to know more about your specific scenario and if you think something like this would be helpful (although perhaps not as straight forward to implement).

**Comment by ericleigh007** [comment]
First, I don't want to trivialize what it will take to do this.
I'm sure that the kind of scale you need to support would be unfathomable to me, but this sort of scale is definitely possible on other services.  My thought would be to have a hashed list of query results that would be a first in first out list if the user has more than one query simultaneously. SQL's OFFSET and FETCH seem to fit that bill somewhat efficiently, and you guys do have probably most performant hardware and storage devices at your service, right?

I guess i'm assuming you've got SQL on the backend.  I just a making the leap based upon the OData support.  The indexer seems to do the trick in Windows with its `GetItemsAsync(startIndex, FILE_READ_BATCH_SIZE)` construct of `StorageItemQueryResult`

You mention "you can calculate and know where you want to be".  If by "you", you're referring to the app, then that app ONLY knows the index of where the control is when the user scrolls, but it knows that EXACTLY.

I need to amend my description earlier by one point.  I would also need the $count return from the OData query because that would tell me where to size the virtual control (or my ultimate list, which might be virtualized more levels, to keep things even tighter in memory to support smaller memory devices)

From a standpoint of "telling you where we need to be in results", the skip would be based on getting callbacks from the control using the interfaces I mentioned, which indicate which items are visible.  The control doesn't know anything except item number about where it is in the list.

You're right that there are alternatives, but they all would require more round trips to the server, and MORE queries (considering with small to medium number of matches, the "skip" would just issue the cached results, and not strictly do another query).  Even though the OneDrive servers are going to need cache memory or device,, they still can deal with that a lot better than devices can deal with having to grab down the entire list and place it in memory.

There is of course the thought of reading down information and putting it in some local database.  Unfortunately, that database would need to be kept up to date, meaning that as users uploaded data, we'd have to know when the correct the database (and there isn't any way to do that on the fly -- the best we can do is look for changes every so often). Supporting a local database scenario would mean that the app has to worry about the inevitable problem of the database andt the OneDrive data getting out of sync, and providing some way to reset things.  Ugh!

Another option that comes to mind is chunking out data by date, or by name (date is liable to give the best results because names are something like IMG_* or w*.  for pictures (which are probably the most common items in OneDrive))., BUT...

Chunking items by date doesn't seem as if it approaches the interactivity that a user would want when trying to zip around and see a picture they are interested in.  After all, unless one knows where the pictures for a specific date start, the app cannot even do a query to get that date's pictures.  In other words, a user quickly scans through 500 pictures as thumbnails and overruns where we have data loaded (think of flipping through a set fo 1000 pages of pictures in your hand, and stopping on the correct one, or near it, and then adjusting.  This needs to be as near instantaneous as possible).  When they stop scrolling, we don't know what date we need in order to refresh the data.  Using date for this scenario is a chicken or the egg problem.

In the best of all words, you guys would just implement $skip AND $count per the spec.  This has the great advantage of being standards compliant, so devs won't immediately lament that OneDrive is different than every other service out there.

If it helps at all, one thing that I could think of that could be acceptable is to control the granularity of the skip by enabling the return of a "page" of data (this is what Flickr appears to do).   Something like items_per_page=500 page_number=56, and that means I'd just grab full pages of data at fixed offsets, sometimes downloading metadata for pictures I didn't need (only grabbing for content based on the Interface callbacks in the control, of course).

I don't want to fail to mention that what I'm proposing is exactly what the UWP photos app seems to already do.  You can see by zipping up to 1000 then back to 700 or so in the photos interface that it is loading in chunks per the Random Access Data Virtualization pattern.  So if photos is enabled to do this, how is OneDrive supporting it?  Hopefully not with some closed proprietary interface we developers cannot benefit from.  Looking at Onedrive.com, one appears to see the same pattern of loading chunks.  Do my eyes deceive me?

I hope that I've helped to explain my conundrum.

If you think it would be useful to have a call on this, I can support that.

**Comment by ericleigh007** [comment]
Anything new on this?  Further comments?  I know we can do it!  (somehow)

-e

**Comment by ericleigh007** [comment]
17 days goes by... any update?

**Comment by ginach** [comment]
@ericleigh007, I've moved this to the [API docs repo](https://github.com/OneDrive/onedrive-api-docs/issues/324) since this is an API feature request.
