### ISSUE TITLE
How to Authenticate in ASP.NET with Business Account using SDK 

### ISSUE THREAD

**Issue by ghost** [OneDrive/onedrive-sdk-csharp#45]
Do you have a guide on how to do this?

I tried to use the simple authentication below
var oneDriveClient = OneDriveClient.GetMicrosoftAccountClient(
                         clientId,
                         returnUrl,
                         scopes);

await oneDriveClient.AuthenticateAsync();

I noticed that after creating the client, the ClientType is set as "Consumer"

I read in this Issue 
https://github.com/OneDrive/onedrive-sdk-csharp/issues/23

That I might to create a class that implements IWebAuthenticationUi
Do you have a sample for that?

many thanks
Philip

**Comment by ginach** [comment]
Correct, `GetMicrosoftAccountClient` returns a OneDrive Consumer client. What you'll want to look into are the static methods in `BusinessClientExtensions`. The [auth documentation](https://github.com/OneDrive/onedrive-sdk-csharp/blob/master/docs/auth.md) has examples of creating a OneDrive for Business client under "Azure Active Directory (AAD) authentication".

Here's an example of creating a client using client ID and return URL:

```csharp
var oneDriveClient = BusinessClientExtensions.GetActiveDirectoryClient(clientId, returnUrl);

await oneDriveClient.AuthenticateAsync();
```
This will use the [Discovery Service](https://msdn.microsoft.com/en-us/office/office365/howto/discover-service-endpoints) to look up the service resource ID for authentication as well as the correct base URL for the API endpoint. If you do know these values already you can bypass the Discovery Service by providing them directly:

```csharp
var oneDriveClient = BusinessClientExtensions.GetActiveDirectoryClient(
    clientId,
    returnUrl,
    oneDriveApiEndpoint,
    serviceResourceId)

await oneDriveClient.AuthenticateAsync();
```
The SDK is currently using [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet) for Business authentication.

**Comment by philip-yao-yooba** [comment]
Hi Gina, 

I get this exception after calling AuthenticateAsync()

{"AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'.\r\nTrace ID: aa40c0d3-81bd-426d-b010-d777dc4a8d44\r\nCorrelation ID: 445f734b-af2e-46fe-8eaf-41c52eee3974\r\nTimestamp: 2016-01-07 06:48:58Z"}

But the constructor does not accept ClientSecret and the oneDriveClient ClientSecret is readonly

**Comment by philip-yao-yooba** [comment]
I am also getting this error

Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application.

**Comment by ginach** [comment]
Authentication using client secret isn't fully implemented yet. Issue #34 is tracking this and I'm working on it this week. Apologies for the delay in this.

The best way to unblock would most likely be to use ADAL directly to obtain the token and build your own IAuthenticationProvider implementation that just appends it to requests. The AdalAuthenticationProvider class is the right place to start if you want to see what's there at the moment.

**Comment by skobba** [comment]
Hi @ginach, how is it going with the client secret support? I'm using the SharePointClient at the moment, but cound not figure out how to access shared files and folders in my MVC Web App. Will this be easy in the new implementation, like the Graph API? Cheers!

**Comment by zuhaibshafi** [comment]
Hi Ginach, I currently can't find a way to authenticate OneDrive from ASP.NET MVC. Is there any sample available yet?

**Comment by ginach** [comment]
Our [webhooks sample](https://github.com/OneDrive/onedrive-webhooks-aspnet) is an example MVC app.
