### ISSUE TITLE
Unable to authenticate from ASP.Net (OneDrive Personal) using token flow

### ISSUE THREAD

**Issue by Shakeebmm** [OneDrive/onedrive-sdk-csharp#46]
I am using below code to get authenticated for OneDrive Personal from ASP.NET application.

Task<IOneDriveClient> oneDriveClient = OD.OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(
                "{client id}",
                "https://login.live.com/oauth20_desktop.srf", 
                new[] { "onedrive.readwrite" },
                "{client secret}",
                serviceInfoProvider: new OD.ServiceInfoProvider(new AuthenticationProvider("{client secret}"))
        );
            
            IOneDriveClient client = oneDriveClient.Result;
            AccountSession session = await client.AuthenticateAsync();

--> AccessToken comes as NULL here.	What could be the issue here?		

------------------------------------------------------------------------------------

 public class AuthenticationProvider : OD.IAuthenticationProvider
    {
        OD.AccountSession m_session;

        public AuthenticationProvider(string refreshToken)
        {
            m_session = new OD.AccountSession()
            {  
                RefreshToken = refreshToken,
                ExpiresOnUtc = DateTime.SpecifyKind(DateTime.MaxValue, DateTimeKind.Utc),
                ClientId = "{client id}",
                Scopes = new[] { "onedrive.readwrite" },
                AccountType = OD.AccountType.MicrosoftAccount
            };
        }

        public OD.AccountSession CurrentAccountSession
        {
            get
            {
                return m_session;
            }

            set
            {
                m_session = value;
            }
        }

        public Task AppendAuthHeaderAsync(HttpRequestMessage request)
        {
            request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue(OD.Constants.Headers.Bearer, m_session.AccessToken);
            return Task.WhenAll(); // == Task.CompletedTask
        }

        public Task<OD.AccountSession> AuthenticateAsync()
        {
            return Task<OD.AccountSession>.FromResult(m_session);
        }

        public Task SignOutAsync()
        {
            throw new NotImplementedException();
        }
    }

**Comment by ginach** [comment]
AppendAuthHeaderAsync is what the code calls to attach the auth header to a request. In your code, the constructor always creates an AccountSession that has no access token and you're attaching that to the request:

```csharp
public Task AppendAuthHeaderAsync(HttpRequestMessage request)
    {
        request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue(OD.Constants.Headers.Bearer, m_session.AccessToken);
        return Task.WhenAll(); // == Task.CompletedTask
    }
```

What you want to do is use the authentication provider already implemented in the code. Calling GetSilentlyAuthenticatedMicrosoftAccountClient without passing your own IAuthenticationProvider implementation will do this:

```csharp
var client = await OD.OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(
    "{client id}",
    "https://login.live.com/oauth20_desktop.srf",
    new[] { "onedrive.readwrite" },
    "{client secret}";

var session = await client.AuthenticateAsync();
```

If you do want to use your own IAuthenticationProvider you'll either want to inherit from AuthenticationProvider since it will still retrieve the access token for a refresh token for you or implement the logic to retrieve an access token using the refresh token yourself.

**Comment by Shakeebmm** [comment]
Application hangs after

var client = await OD.OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(
    "{client id}",
    "https://login.live.com/oauth20_desktop.srf",
    new[] { "onedrive.readwrite" },
    "{client secret}");

And no response after this.

**Comment by Shakeebmm** [comment]
I am able to get the response now, but its throwing attached error.
![image](https://cloud.githubusercontent.com/assets/16578127/12171375/54a5ed34-b56f-11e5-949d-e13ccacc90f4.png)
