### ISSUE TITLE
Authenticate without any user interaction in C# windows forms

### ISSUE THREAD

**Issue by Shakeebmm** [OneDrive/onedrive-sdk-csharp#49]
How do get authenticated without any user interaction from C# windows forms? Tried below code, but its asking for the confirmation.

 this.oneDriveClient = OneDriveClient.GetMicrosoftAccountClient(
                        FormBrowser.MsaClientId,
                        FormBrowser.MsaReturnUrl,
                        FormBrowser.Scopes,
                        webAuthenticationUi: new FormsWebAuthenticationUi());

**Comment by ginach** [comment]
Are you trying to build an app that never prompts the user for auth or one that only prompts initially instead of asking every time the user opens the app?

**Comment by Shakeebmm** [comment]
I am trying build an windows application which never prompts the user for auth.

**Comment by ginach** [comment]
Unfortunately, Microsoft Account OAuth doesn't support flows that never prompt the user.

Our recommended approach is to use refresh tokens for auth when an app can't handle UI. The user needs to be prompted for the initial auth, like from a sign up page, but if you request the wl.offline_access scope that authentication will return a refresh token that's good for up to a year. You can then use this to get an authenticated client using the refresh token:

```csharp
await OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(
    clientId,
    returnUrl,
    scopes,
    refreshToken)
```
A new refresh token will be set in the account session any time a new access token is retrieved, each one expiring a year from issue.

**Comment by Shakeebmm** [comment]
I am trying to authenticate and create a folder. I have tried below 2 approaches, but both giving error ("An error occurred sending the request.") at 
 var newFolder = await this.oneDriveClientNew.Drive.Items["root"].Children.Request().AddAsync(folderToCreate); line. 
 
 Could you please help?
 
 Scopes used : { "onedrive.readwrite", "wl.offline_access", "wl.signin" };
 
 Approach 1
 ---------------------------------------------------------------------------------
 
 this.oneDriveClient = OneDriveClient.GetMicrosoftAccountClient(
                        FormBrowser.MsaClientId,
                        FormBrowser.MsaReturnUrl,
                        FormBrowser.Scopes,
                        webAuthenticationUi: new FormsWebAuthenticationUi());

if (!this.oneDriveClient.IsAuthenticated)
	{
		var session = await this.oneDriveClient.AuthenticateAsync();
		var folderToCreate = new Item { Name = "My folder1", Folder = new Folder() };
		var newFolder = await this.oneDriveClient.Drive.Items["root"].Children.Request().AddAsync(folderToCreate);
	}

	
	
 Approach 2
 ---------------------------------------------------------------------------------
 
 this.oneDriveClient = OneDriveClient.GetMicrosoftAccountClient(
                        FormBrowser.MsaClientId,
                        FormBrowser.MsaReturnUrl,
                        FormBrowser.Scopes,
                        webAuthenticationUi: new FormsWebAuthenticationUi());

if (!this.oneDriveClient.IsAuthenticated)
	{
		var session = await this.oneDriveClient.AuthenticateAsync();

		this.oneDriveClientNew = await OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(
			 FormBrowser.MsaClientId,
			 FormBrowser.MsaReturnUrl,
			 FormBrowser.Scopes,
			 session.RefreshToken);

		await this.oneDriveClientNew.AuthenticateAsync();

		var folderToCreate = new Item { Name = "My folder1", Folder = new Folder() };
		var newFolder = await this.oneDriveClientNew.Drive.Items["root"].Children.Request().AddAsync(folderToCreate);

	}
