### ISSUE TITLE
Upload to SpecialFolder

### ISSUE THREAD

**Issue by minimalisticMe** [OneDrive/onedrive-sdk-csharp#52]
Hi,
I can upload files successfully via 
`item = await oneDriveClient.Drive.Root.ItemWithPath(itemPath).Content.Request().PutAsync<Item>(memStream);`
to the OneDrive directory. However, when I want to upload to SpecialFolder Approot both:
`var specialFolder = await this.oneDriveClient.Drive.Special.AppRoot.Request().GetAsync();
if(specialFolder != null)
{
  item = await oneDriveClient.Drive.Items[specialFolder.Id].Content.Request().PutAsync<Item>(memStream);
}`
and
`item = await oneDriveClient.Drive.Special.AppRoot.ItemWithPath(itemPath).Content.Request().PutAsync<Item>(memStream);`
fail.
I do get an Error saying "Exception of type 'Microsoft.OneDrive.Sdk.OneDriveException' was thrown." with Stacktrace:

"   at Microsoft.OneDrive.Sdk.HttpProvider.<SendRequestAsync>d__16.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.OneDrive.Sdk.HttpProvider.<SendAsync>d__14.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.OneDrive.Sdk.BaseRequest.<SendRequestAsync>d__29.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.OneDrive.Sdk.BaseRequest.<SendAsync>d__27`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at OneDriveClass.myOneDrive.<uploadObject>d__8`1.MoveNext()"

**Comment by ginach** [comment]
Could you provide the details of the exception's Error.Code and Error.Message properties?

**Comment by minimalisticMe** [comment]
Sure, `OneDriveException e` has the properties:
`e.Error`: Code = "invalidRequest", Message = "Item does not match expected type", AdditionalData and InnerError is null.
How can I assist further or where can I find more usefull information to share?

**Comment by ginach** [comment]
Could you send the value of the X-ThrowSite header in the API response?

**Comment by JimiC** [comment]
`var specialFolder = await this.oneDriveClient.Drive.Special.AppRoot.Request().GetAsync();` will not get you the file info but the folder info.
Therefore `if(specialFolder != null) { item = await oneDriveClient.Drive.Items[specialFolder.Id].Content.Request().PutAsync<Item>(memStream); }` will fail as you are not telling it the file id.
On the other hand `item = await oneDriveClient.Drive.Special.AppRoot.ItemWithPath(itemPath).Content.Request().PutAsync<Item>(memStream);` will succeed as long as you uri escape the `itemPath` (i.e. ```Uri.EscapeUriString(filename)```)

**Comment by minimalisticMe** [comment]
@JimiC the code snippet is working. 
Further does the problem not rely on the API, it was my fault. 

I tried to upload the same stream to both to Root and AppRoot for debug purposes and was using the same stream *memStream* without setting it's position back to 0 after uploading it the first time, so the second time of cause it crashed.

The ticket can be closed. I'm sorry for the inconvenience.
