### ISSUE TITLE
How to get link to see the original image

### ISSUE THREAD

**Issue by Shakeebmm** [OneDrive/onedrive-sdk-csharp#54]
I want upload an Image and get a link which never expires to access the original image (this feature is available in Google Drive). Any one with this link should be able to see the original image.

**Comment by cyberh0me** [comment]
what you need is already possible
1) upload (https://dev.onedrive.com/items/upload_put.htm)
2) share (https://dev.onedrive.com/items/sharing_createLink.htm)
of course your app need the required permissions...

**Comment by ginach** [comment]
@Shakeebmm , please re-open if the above answer doesn't address your issue.

**Comment by Shakeebmm** [comment]
Hi,

This doesn't address the my problem :(

**Comment by cdmayer** [comment]
What about this solution is not solving your problem?

**Comment by Shakeebmm** [comment]
Nope. I need the API details to do this.

**Comment by cdmayer** [comment]
The API details are in the links provided above. Have you successfully created a sharing link? Can you give me more details as to what is going wrong?

**Comment by Shakeebmm** [comment]
- Does the shared link expires any time?
- Will it ask user to enter credentials?
- Will it display the original image in browser with out any One Drive options? (Like the URL provided by Google Drive "https://drive.google.com/uc?id=0B-gtOmC3pYFpV2JWVm1IX0Zldzg")

**Comment by Shakeebmm** [comment]
Please find the C# code which I am using.

## Log on with refresh token.
this.oneDriveClientNew = await OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(
                           frmOneDrivePOC.MsaClientId,
                           frmOneDrivePOC.MsaReturnUrl,
                           frmOneDrivePOC.Scopes,
                           RefreshToken);

## Get target folder
var expandString = "thumbnails,children(expand=thumbnails)";
var targetFolder = await this.oneDriveClientNew.Drive.Items["AB5F3893F04A3B5D%21120"].Request().Expand(expandString).GetAsync();

## Get image file stream to upload
var stream = GetFileStreamForUpload(out strImageName)

## Upload the stream
string folderPath = targetFolder.ParentReference.Path + "/" + Uri.EscapeUriString(targetFolder.Name);
var uploadPath = folderPath + "/" + Uri.EscapeUriString(System.IO.Path.GetFileName(strImageName));
var uploadedItem = await this.oneDriveClientNew.ItemWithPath(uploadPath).Content.Request().PutAsync<Item>(stream);

**After uploading image, I need the sharable link**

**Comment by cdmayer** [comment]
This is definitely possible. It actually resulted in PR #137, which added `.Root` to `ShareRequestBuilder`. You will need those changes in order to do what you want to do. The Nuget package won't be up to date with these new changes yet, so you may need to clone and build the project on your own.

In the example below, I assume that you have already uploaded an `Item` (as shown in your sample code).

```
var linkPermission = await client.Drive.Items[uploadedItem.Id].CreateLink("view").Request().PostAsync();
var shareItem = await client.Shares[link.ShareId].Root.Request().Expand("thumbnails").GetAsync();
```

The links you desire will be available in `shareItem.Thumbnails.CurrentPage.First().Large.Url`. The link will live until you stop sharing or delete the item.
