### ISSUE TITLE
Support upload using background upload APIs on UWP

### ISSUE THREAD

**Issue by ginach** [OneDrive/onedrive-sdk-csharp#56]

**Comment by ericleigh007** [comment]
Hello all,
As I mentioned in another thread, I have the UWP background uploads working in a way that didn't require any OneDrive SDK changes.
If it will be of any help, you're welcome to that.
As for the large file (chunked) upload, I would wonder if you guys are going to do it soon.  If not, I won't bother with it.
I already have the backgroundTask that I needed to auto-upload pictures from the camera roll.  From there, I queue my single-part, up to 100MB uploads.  To get the chunked uploads working that we'll need for massive videos, I was going to keep the BackgroundTransfer logic I have, but assign a completiongroup to the transfer so my background task gets called again when that completes.  Basically, each time I get the completion group invocation, I was going to do a background upload of the next hunk of data, and repeat that until the entire file is uploaded.

If you can, let me know rough timing of what you guys plan to do?

-thanks
-e

**Comment by nitinphansalkar** [comment]
Hi,

I would like to provide a facility for the users of my UWP app to upload videos (> 100 MB) to OneDrive and I was looking for a sample code to accomplish large file uploads using OneDrive SDK (C#). I could not locate any sample but for a method to create an `UploadSession`. I would highly appreciate if a sample is provided. This will help me to publish my App at the earliest. Thanks!
P.S. I have posted a question on StackOverflow as well: http://stackoverflow.com/questions/36551048/uwp-upload-large-files-to-onedrive-using-onedrive-sdk

**Comment by ginach** [comment]
Hi @nitinphansalkar,

You might want to take a look at [this issue](https://github.com/OneDrive/onedrive-sdk-csharp/issues/21) for an example of using the BackgroundUploader and [this StackOverflow answer](http://stackoverflow.com/questions/33408692/cannot-upload-to-onedrive-using-the-new-sdk/33701793#33701793) for an example of creating an upload session for chunked upload.

**Comment by cdmayer** [comment]
#176 added large file uploads.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
