### ISSUE TITLE
Fail to request item content into stream after updating to 1.1.29

### ISSUE THREAD

**Issue by xiaomi7732** [OneDrive/onedrive-sdk-csharp#57]
Same code works with 1.1.20 but throws exception on 1.1.29. syncFileItem.Id can be fetched correctly. Is there API change or is this a bug?

        var contentStream = await oneDriveClient.Drive
                    .Items[syncFileItem.Id]
                    .Content
                    .Request()
                    .GetAsync();

Exception:
Message	"The request is not supported. (Exception from HRESULT: 0x80070032)"	string
		StackTrace	"   at Windows.Security.Authentication.OnlineId.OnlineIdAuthenticator.AuthenticateUserAsync(OnlineIdServiceTicketRequest request)\r\n   at Microsoft.OneDrive.Sdk.OnlineIdAuthenticationProvider.<GetAccountSessionAsync>d__4.MoveNext()"	string

Authentication related code:

            return OneDriveClientExtensions.GetClientUsingOnlineIdAuthenticator(new string[] {
                "wl.signin", "onedrive.appfolder", "onedrive.readwrite"
            });

Please help take a look.

**Comment by ginach** [comment]
This is odd. OnlineIdAuthenticationProvider wasn't touched with the latest version change. When you downgrade the Nuget package are you seeing it work again?

**Comment by xiaomi7732** [comment]
Thanks for the reply. Yes, when downgrade it to 1.1.20, it starts to work again. And the downgrade (by editing project.json) is the only action that is needed to make the code work.

**Comment by ginach** [comment]
Ok, thanks for reporting. I'll take a look.

**Comment by xiaomi7732** [comment]
Anyone do me a review on the pull request?

**Comment by ginach** [comment]
This should be fixed with the latest package push.
