### ISSUE TITLE
Don't show splash screen on sign out

### ISSUE THREAD

**Issue by JimiC** [OneDrive/onedrive-sdk-csharp#58]
I have noticed that when signing out the `FormsWebDialogs` is shown briefly. Although it's not an issue per say, it would satisfy my OCD, it it wasn't shown.

@ginach 
In case you agree to that I can provide a PR to deal with that.
Experimentally I have done so by adding a switch at line 60 of `FormsWebDialog.GetAuthenticationResponseValues`. The switcher also requires a new boolean parameter on the method.
Thoughts?

**Comment by ginach** [comment]
Sounds good to me, please do send a PR.

**Comment by JimiC** [comment]
Found a better to deal with it without touching to method signature.

**Comment by JimiC** [comment]
This issue failed to close automatically. Closing it manually.
