### ISSUE TITLE
Scope: "wl.signin", what's it useful for?

### ISSUE THREAD

**Issue by JimiC** [OneDrive/onedrive-sdk-csharp#59]
I can't seem to figure out what the scope "wl.signin" does.
Can anyone elaborate?

**Comment by minimalisticMe** [comment]
see [Scopes and permissions](https://msdn.microsoft.com/en-us/library/hh243646.aspx?f=255&MSPPError=-2147217396) for what some permissions mean.

**wl.signin** provides single sign on and works like the following: The first time, your user signs in once with your app, he has to enter his credentials and give your app access. Now with **wl.signin** in your scopes, the next time, you want to access his oneDrive, he does not need to give you permission again, as you already got them once (single sign on). Without that permission, the next time, the user logs in, he/she would have to enter credentials again.

**Comment by JimiC** [comment]
From the link you supplied:
> wl.signin: Single sign-in behavior. With single sign-in, users who are already signed in to Live Connect are also signed in to your website.

The fact is that if I'm already signed in via SSO in OneDrive web app I still get a request to sign in via the SDK pop window. Doesn't make sense. Note here that I'm using the SDK for a winforms app.

**Comment by JimiC** [comment]
I think I got it.

Once I have signed in once (without signing out), the next time I request a client the same way, I won't get the sign in window but go straight to the permissions consent one.

Pretty useless in my case but still glad I figured it out.

**Comment by JimiC** [comment]
Turns out this is not the case (as I mentioned above) but what the heck.
