### ISSUE TITLE
requesturi missing access_token

### ISSUE THREAD

**Issue by cyberh0me** [OneDrive/onedrive-sdk-csharp#61]
i would expect the command
```csharp
OneDrive.Drive.Items["id"].Content.Request().GetHttpRequestMessage().RequestUri
```
include the access_token but thats not the case, it "only" provides the full uri but thats senseless without the access_token as we need the access_token to fullfill the request...

i try to connect a mediaelement to the music stored on onedrive
```csharp
 MediaElement.Source = OneDrive.Drive.Items["id"].Content.Request().GetHttpRequestMessage().RequestUri;
```
because the access_token is missing i would need to extend that command to include
```csharp
OneDrive.AuthenticationProvider.CurrentAccountSession.AccessToken
```
to build a working url but why should i need to build an uri outside of the sdk 

or is there a better way to connect a mediaelement with music located on onedrive by use of the onedrive csharp sdk?

**Comment by ginach** [comment]
The SDK passes the access token as a header, not a query string, which is why that property doesn't include it. I understand the use case you're describing so marking as enhancement to add an extension for getting the request URL with access token.

With the current SDK functionality you have a couple options:

1. Append the access token yourself like you mention.
2. Get an item, selecting @content.downloadUrl, and use that URL for the MediaElement source:

```csharp
var item = await client.Drive.Items["id"].Request().Select("@content.downloadUrl").GetAsync();
MediaElement.Source = item.AdditionalData["@content.downloadUrl"] as string;
```
The second option does require a second network call but the URL returned is pre-authenticated to last the duration of the access token.

**Comment by rgregg** [comment]
This scenario is best supported by using @content.downloadUrl.

Using the access_token in the query string isn't supported for OneDrive for Business and thus the SDK doesn't encourage that usage pattern.

**Comment by cyberh0me** [comment]
thank you

**Comment by cyberh0me** [comment]
unfortunately
var item = await client.Drive.Items["id"].Request().Select("@content.downloadUrl").GetAsync();
raise a bad argument onedriveexception 
and if i try
var item = await Cloud.OneDrive.Instance.Client.Drive.Items["id"].Request().GetAsync()
and check item is content = null

**Comment by cyberh0me** [comment]
unfortunately
```csharp
var item = await client.Drive.Items["id"].Request().Select("@content.downloadUrl").GetAsync();
```
raise a bad argument onedriveexception
```csharp
item = await Cloud.OneDrive.Instance.Client.Drive.Items["id"].Request().GetAsync();
media.Source = new Uri(item.AdditionalData["@content.downloadUrl"] as string);
```
works

**Comment by ginach** [comment]
It turns out there's a bug in the API where select statements starting with "@" are erroring. The above works, like you said, but if you want to cut down response size you can do something like Select("id,@content.downloadUrl") to work around the API bug.

**Comment by cyberh0me** [comment]
should i reopen this issue or do you create another issue to handle that bug?
i have closed this one as it works for me and i can live with 2 webrequests... even if i would prefer to have the possibility to store a song link in a local database but i afraid that's not supported from onedrive itself (the content.downloadUrl always changes)
