### ISSUE TITLE
Can't get shared collections

### ISSUE THREAD

**Issue by SBQuintanar** [OneDrive/onedrive-sdk-csharp#64]
One user shared with me a folder with a couple files inside.
I have added the folder to my OneDrive.
I can see the folder listed in it's parent's IChildrenCollectionPage, but cannot retrieve the items inside of it. The next code returns an empty IChildrenCollectionPage:
    await this.OneDriveClient.Drive.Items[folderId].Children.Request().GetAsync();

Is it possible get the files in that folder?

**Comment by ginach** [comment]
The children of a remote item need to be enumerated via the item's actual location. For example, var children = await client.Drives[driveId].Items[folderId].Children.Request().GetAsync();

The SDKs need to be updated for some of the newer API features, like remote items. I've opened #65 to track the update for this SDK. For now, any extra properties like this are deserialized into the AdditionalData property of the item. Interacting with this isn't ideal but should allow you to work around things until RemoteItem is available.

**Comment by SBQuintanar** [comment]
Hi, @ginach.
Thanks! Reading the AdditionalData info works.

Now, if I get read-only access to a specific folder, it cannot be added to my OneDrive.
Is there any way to access these files by having the ItemId, ParentDriveId and public AuthKey in the shared link?

**Comment by ginach** [comment]
Unfortunately the API doesn't have a way to do that at the moment. Please feel free to open an issue in the [API docs repo](https://github.com/OneDrive/onedrive-api-docs) and/or add the request to our [User Voice page](https://onedrive.uservoice.com/forums/262982-onedrive/category/89523-developer).

**Comment by ginach** [comment]
Closing this issue and using #65 to track updating the SDK for our January release.
