### ISSUE TITLE
authentication_failed

### ISSUE THREAD

**Issue by kida7** [OneDrive/onedrive-sdk-csharp#67]
Cant login, error message: 
An error occurred during active directory authentication. Error: authentication_failed. Description: Stream does not support seeking.

**Comment by JimiC** [comment]
You have not configured the client correctly. Post a code sample of your implementation and I might be able to assist you further.

**Comment by kida7** [comment]
When I run the example "WinStore", after press the button "Log in to AAD", enter my account, login and get that log at output console. I do not change anything.

**Comment by ginach** [comment]
This is a bug in ADAL: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/257. It looks like the latest ADAL package has the fix so I'll upgrade the dependency.

**Comment by ginach** [comment]
Closing issue since you can update the version of ADAL your project is referencing to fix the issue. Please re-open if that doesn't address your issue.
