### ISSUE TITLE
Can't sign out acc

### ISSUE THREAD

**Issue by kida7** [OneDrive/onedrive-sdk-csharp#69]
When I call OneDriveClient.SignOutAsync(); but OneDriveClient.IsAuthenticated value is still true. So how to sign out account

**Comment by ginach** [comment]
AccountSession has a CanSignOut value on it stating whether or not the user is able to sign out. If using OnlineIdAuthenticator sign out may not be available. This is in the case where the account is connected to the machine or device being used for authentication. In other cases, sign out should be available.

**Comment by ginach** [comment]
Please re-open if the above answer didn't resolve this issue.
