### ISSUE TITLE
Cached Account Session

### ISSUE THREAD

**Issue by cmakthat** [OneDrive/onedrive-sdk-csharp#70]
I'm developing a UWP app and I'm using OneDriveClientExtensions.GetAuthenticatedClientUsingWebAuthenticationBroker to log in. I am able to login successfully and log out as well. Although, let's say I login, the app closes completely and I relaunch the app. Now I no longer have the previous account session to log out. If I try calling "GetAuthenticatedClientUsingWebAuthenticationBroker" again, the "Connecting to service" dialog comes up again to login which is not what I would expect since I have a previous session. I've seen the function "GetSilentlyAuthenticatedMicrosoftAccountClient" but I don't receive a refresh token back from the initial login. Any suggestions for this use case?

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
