### ISSUE TITLE
AuthenticationFailure after upgraded from 1.1.20 to 1.1.29

### ISSUE THREAD

**Issue by kinex** [OneDrive/onedrive-sdk-csharp#73]
I think there is some authentication issue in 1.1.29. Everything seems to work well until I call 
`client.Drive.Request().GetAsync()` which throws `AuthenticationFailure`. I could not find release notes to check if this is related to some planned change. I reverted back to 1.1.20 which solved the issue. Code sample to reproduce the issue:
`var client = OneDriveClientExtensions.GetUniversalClient("wl.signin", "wl.offline_access", "onedrive.readwrite", "onedrive.appfolder");`
`var session = await client.AuthenticateAsync();`
`var drive = await client.Drive.Request().GetAsync();`

**Comment by kinex** [comment]
Actually this is probably same issue as #57.

**Comment by ginach** [comment]
I still haven't narrowed this issue down. Could you give me more details to help investigate?

1. What happens when you try using OneDriveClientExtensions.GetAuthenticatedClientUsingWebAuthenticationBroker instead? Does authentication succeed or fail?

2. Are you using a Microsoft account that's connected to the local machine already?

3. Is the inner exception the same as issue #57?

**Comment by kinex** [comment]
1.  OneDriveClientExtensions.GetAuthenticatedClientUsingWebAuthenticationBroker throws OneDriveException with error "AuthenticationCancelled" (same error also in 1.1.20), but it is unclear to me what the first param "appId" should be. I tried using the ID that is available from OneDrive app registration page and the ID at end of my test app's Store URL.

In my original code the calls `GetUniversalClient` and `AuthenticateAsyhnc` succeed (returned objects seem to contain valid data), it is the call `client.Drive.Request().GetAsync()` which fails to exception.

2. Yes, I use the same Microsoft account that I use to login into my development PC (Windows 10.0.10586)

3. Yes.

**Comment by NPadrutt** [comment]
I have the same issue. Is there anything I can do to help find this issue? 
The project is open source, if it helps you to see the code itself.

**Comment by lluppes3M** [comment]
I'm working on a universal app which works fine on my desktop in Windows 10.  When I deploy it to the Win10 IoT Core on a Raspberry Pi, it throws this same error.  I call OneDriveClientExtensions.GetClientUsingWebAuthenticationBroker("{myappid}", _scopes) and it gets an "AuthenticationCancelled" error .  I'm using 1.1.29 also.  Any update on this issue...?

**Comment by ginach** [comment]
@lluppes3M, what you're seeing is different. The reported issue above is using OnlineIdAuthenticator while you're using WebAuthenticationBroker. Could you provide details on how you're creating the client?

**Comment by lluppes3M** [comment]
If I run this same exact code on my Win10 laptop it works fine.  If I run it on the RP3 with Win10 IoT Core, it fails with the "AuthenciationCanceled" error.

        private IOneDriveClient _client;
        private readonly string[] _scopes = { "onedrive.readonly", "onedrive.appfolder", "wl.signin" };
        private AccountSession _session;
        private async Task<bool> GetOneDriveFolderContentsAsync()
        {
            try
            {
                _session = null;
                _client = OneDriveClientExtensions.GetClientUsingWebAuthenticationBroker(
                    "00000000xxxxxxx", _scopes);
                _session = await _client.AuthenticateAsync();
            } 
           ....  <fails before I get to this point...>

**Comment by lluppes** [comment]
@ginach - Any update on this?  I still can't get this to work on an RP3...

**Comment by kinex** [comment]
What is the status of this issue? From my understanding the SDK version 1.1.29 is not usable for UWP apps, so I would consider this as a high priority issue. It works in 1.1.20 but was broken one month later in 1.1.29. So it should not be hard to find the bug.

**Comment by ginach** [comment]
@kinex, unfortunately I still haven't been able to repro this once. Could you give PR #115 a shot and see if it fixes the issue for you?

**Comment by ginach** [comment]
Closing since this is the same issue as #57.

**Comment by kinex** [comment]
Have you tried it (running the above code) in a desktop environment? Strange if it works in your environment. I can try again with the latest sources later (need to publish my UWP app first). I am still using the latest stable version 1.1.20 but I cannot stick into an old version forever.
