### ISSUE TITLE
Large file download - Performance Issue

### ISSUE THREAD

**Issue by prakashguru** [OneDrive/onedrive-sdk-csharp#74]
Hi,
The one drive api is really good and easy to use. And it has lot of customization points where I can easily change some of the behavior. 

I am trying to download a large file > 80MB from one drive using the test application. The process memory is shooting up. 

Is there a way to fix this?

Note: 
Upon further investigation, the call "this.oneDriveClient.Drive.Items[item.Id]. Content.Request().GetAsync() " buffers the file content as MemoryStream. Which was the reason for this issue.

The GetAsync() internally uses HttpClient.SendAsync() which has overload to specify HttpCompletionOption where the download buffering can be skipped. Unfortunately I really don't know how to override that behavior.

**Comment by ginach** [comment]
Thank you for reporting this. You're right that there's no way to override it currently. I'll update here once I've had a chance to look into this.

**Comment by prakashguru** [comment]
Thanks for your response. Is there any workaround?  Because we are going to release the app integration to production next month. 50% of the expected files are large :(.

**Comment by ginach** [comment]
There are a couple workaround options:

- Create your own IHttpProvider implementation and use that in the client. You could even have a OneDrive client you use for large file uploads and a second one for other operations. For this example, assume client1 is the client you're already creating (the specific extension I'm using below is an example, they should all take in an IHttpProvider and IServiceInfoProvider:

```csharp
    var client2 = GetMicrosoftAccountClient(
        appId,
        returnUrl,
        scopes,
        httpProvider: new CustomHttpProvider(),
        serviceInfoProvider: new ServiceInfoProvider(client1.AuthenticationProvider));

    await client2.AuthenticateAsync();
```

- Create an extension method for the particular requests types we're talking about that issues the HTTP call itself. There's probably more configuration you'll want to do here but it should be an OK starting point:

```csharp
public static async Task<Stream> CustomGetAsync(this ItemContentRequest itemContentRequest)
        {
            itemContentRequest.Method = "GET";

            using (var requestMessage = itemContentRequest.GetHttpRequestMessage())
            {
                await itemContentRequest.Client.AuthenticationProvider.AppendAuthHeaderAsync(requestMessage);

                using (var httpClient = new HttpClient())
                {
                    var response = await httpClient.SendAsync(
                        requestMessage,
                        HttpCompletionOption.ResponseHeadersRead);
                    return await response.Content.ReadAsStreamAsync();
                }
            }
        }
```

**Comment by prakashguru** [comment]
Finally I ended up having a custom http provider and with method like you suggested. And manually type casting the onedriveclient.httpprovider to my custom provider and used it.

Thanks for the help. Also there is bug in "BusinessClientExtensions.GetActiveDirectoryClient" the httpProvider parameter is not used. It always creates the default HttpProviderInstance. I have just copied the code inside "GetActiveDirectoryClient" and fixed it.

**Comment by prakashguru** [comment]
I think we can close this issue. There is an implementation available in the ItemContentRequest. GetAsync(CancellationToken, HttpCompletionOption), where we can pass the "HttpCompletionOption.ResponseHeadersRead" for large file downloads.
