### ISSUE TITLE
Pagination - Bug

### ISSUE THREAD

**Issue by prakashguru** [OneDrive/onedrive-sdk-csharp#76]
Hi, 

The following pagination code is not working. The second call will not get the next set of items instead it returns the same set of items as the first one.

`var page = await oneDriveClient.Drive.Items[item.Id].Children.Request().Top(100).Select("name").GetAsync();`
`var nextPage = await page.NextPageRequest.GetAsync();`

By inspecting the fiddler log, The URL generated for the second request is strange,
**URL for the first request** :  
https://abccompany-my.sharepoint.com/_api/v2.0/me/drive/items/01LZHNAUECBE37DBUFN5GLCRHQNCZVXBUX/children?top=100&select=name

**URL for the second request :**
https://abccompany-my.sharepoint.com/_api/v2.0/me/drive/items('01LZHNAUECBE37DBUFN5GLCRHQNCZVXBUX')/children?$skiptoken=Paged=TRUE&p_SortBehavior=0&p_FileRef=personal%2fprakash_abccompany_onmicrosoft_com%2fDocuments%2fLots%20Of%20Data%2fText%20Data-19.txt&p_ID=25&RootFolder=%2fpersonal%2fprakash_abccompany_onmicrosoft_com%2fDocuments%2fLots%20Of%20Data&$top=100&$select=name

The second request resulted in same set of results as the first one.

_**FYI**_
**Response for the first Request**
As per the one drive for business API documentation, The response will have a @odata.nextLink if there are large number of items then the requested items. Below is the @odata.nextlink,

https://abccompany-my.sharepoint.com/_api/v2.0/me/drive/items('01LZHNAUECBE37DBUFN5GLCRHQNCZVXBUX')/children?%24skiptoken=Paged%3dTRUE%26p_SortBehavior%3d0%26p_FileRef%3dpersonal%252fprakash%255fabccompany%255fonmicrosoft%255fcom%252fDocuments%252fLots%2520Of%2520Data%252fText%2520Data%252d19%252etxt%26p_ID%3d25%26RootFolder%3d%252fpersonal%252fprakash%255fabccompany%255fonmicrosoft%255fcom%252fDocuments%252fLots%2520Of%2520Data&%24top=100&%24select=name

There is difference in the query string. The "@odata.nextLink" have only three "&" indicating three query string parameters. But the sdk generated url contains six "&" which resulted in six query string parameters. 

The first skiptoken querystring somewhat missing all of it's token because of that thats why the second request returns the same set of results. 

Looks like there is a bug in the BaseRequest.InitializeUrl(),
` var queryOptions = queryString.Split('&').Select(
                        queryValue =>
                        {
                            var segments = queryValue.Split('=');
                            return new QueryOption(
                                WebUtility.UrlDecode(segments[0]),
                                segments.Length > 1 ? WebUtility.UrlDecode(segments[1]) : string.Empty);
                        });` 
The UrlDecode of segments[1] resulted in adding some additional query string params which resulted in this issue. Once I removed the WebUtility.UrlDecode() for the segments[1] I am able to get the right results. I am not sure whether it is right fix or not but this information may helpful to you.

Is there any workaround for this?

**Comment by ginach** [comment]
Thank you for reporting this. I see what's happening here. The assumption when reading in the next link is that we're going to re-encode when building the outgoing query string but fail to do so. In order to not break existing clients that that may assume they need to do their own query string encoding we'll keep not encoding on output but stop decoding when building the string from an existing URL.

The workaround would be to manipulate the QueryOptions yourself before sending the request, or before adding your own query options:

```csharp
var oldQueryOptions = new List<QueryOption>();
var requestInstance = collectionPage.NextPageRequest as BaseRequest;

oldQueryOptions.AddRange(requestInstance.QueryOptions);
requestInstance.QueryOptions.Clear();

foreach (var option in oldQueryOptions)
{
    requestInstance.QueryOptions.Add(
        new QueryOption(option.Name, WebUtility.UrlEncode(option.Value);
}
```
Releasing an updated package has been delayed due to my set of authentication fixes but I'll have a fix out with that release.

**Comment by ginach** [comment]
Fixed in latest package push.
