### ISSUE TITLE
Console app

### ISSUE THREAD

**Issue by engaro** [OneDrive/onedrive-sdk-csharp#77]
Hi, 

I try to connect OneDrive through console app, but always with the same result: 
Code: AuthenticationFailure
Message: Failed to retrieve a valid authentication token for the user.

My app run in background and I dont want interacion with user. it is possible to do that? only connect with onedrive and upload and download files?

I have seen examples in the SDK but user interaction to accept the permissions .

My code , but I have tried a lot of things

            var oneDriveClient = OneDriveClient.GetMicrosoftAccountClient(
                         clientId,
                         returnUrl,
                         scopes );

            await oneDriveClient.AuthenticateAsync();

Thank you for your help.

**Comment by ginach** [comment]
Microsoft account doesn't offer an OAuth flow that requires no authentication at all. The user needs to consent to use the application at least initially. For apps like yours our recommendation is to have some sort of "Connect with OneDrive" service where the user can sign up and complete the OAuth flow. If you request the wl.offline_access scope during that flow you'll get a refresh_token that you can then store and use to retrieve access tokens silently later on.

Our [webhooks sample](https://github.com/rgregg/onedrive-webhook-sample/tree/dev) is an example of an app that does this.

**Comment by engaro** [comment]
Thank you very much for answering so fast Ginach. I have changed my first option  by that, and now works fine with refresh_token .

With your examples and a bit of work, I have made the ​​integration!

thank you!
