### ISSUE TITLE
Unable to copy an item without giving a new item name

### ISSUE THREAD

**Issue by shahmalav** [OneDrive/onedrive-sdk-csharp#80]
I am trying to copy an item from one folder to another folder. In the [OneDrive Copy documentation](https://dev.onedrive.com/items/copy.htm) , it states that the name argument is optional. However, in this SDK, it is required to provide a new item name. Am I wrong or or its not possible without providing a new item name? 

` var asyncStatus = await ODClient
                            .Drive
                            .Items[selectedItem.UniqueId]
                            .Copy(newItemName, new ItemReference {  Id = destFolderId })
                            .Request()
                            .PostAsync();`

**Comment by ginach** [comment]
Thanks for reporting this. There's an issue with how the request builder is generating. The API allows not specifying a name, though, so you can pass null to the request builder:

```csharp
var asyncStatus = await ODClient .Drive .Items[selectedItem.UniqueId] .Copy(null, new ItemReference { Id = destFolderId }) .Request() .PostAsync();
```

**Comment by shahmalav** [comment]
It worked! Thanks.
