### ISSUE TITLE
Hosting a website across multiple user's OneDrive accounts

### ISSUE THREAD

**Issue by dumbledad** [OneDrive/onedrive-sdk-csharp#82]
I'm developing a phone app that involves users sharing collections of enhanced photos. Our original plan was to store the photos ourselves in leased Azure blob storage, but a team member has suggested that we instead save the enhanced photos out to our users' Dropbox / Google Drive / OneDrive accounts. Our website would still allow people to share their collections, but the images on our website would be hosted in each user's Dropbox / Google Drive / OneDrive account.

Is this allowed for OneNote? The OneNote SDK has a Thumbnail.Large property which gives me a direct URL to a large thumbnail of an image on OneDrive, but is it OK to use that as the image src in my apps website? It [appears to be OK with Dropbox](https://www.dropboxforum.com/hc/en-us/community/posts/204758803-Hosting-a-website-across-multiple-user-s-Dropbox-accounts), but I wanted to check that this usage scenario—a site whose image assets are spread across all its users' OneDrive accounts—is OK with OneDrive?

**Comment by ginach** [comment]
Hi @dumbledad,

This is more of an API question than an SDK question as it's about allowed and suggested usage of the service. Could you post your question over in the [API docs](https://github.com/OneDrive/onedrive-api-docs/issues) repo?

**Comment by dumbledad** [comment]
[Done](https://github.com/OneDrive/onedrive-api-docs/issues/335#issue-146218682).
