### ISSUE TITLE
What are the options for creating a custom credential cache

### ISSUE THREAD

**Issue by codeRecap** [OneDrive/onedrive-sdk-csharp#83]
I'm working on an application which consists of two parts - a Desktop Application and a Windows Service. They both work with OneDrive via the OneDrive SDK. I'd like the authentication to occur only once, through the Desktop App, but in a way that would allow the Windows Service to use the same credentials that were retrieved via the Desktop App. For this, I'd like to be able to serialize the credentials to a file accessible from both applications. This should be achieved via a custom Credential Cache implementation, but as far as I see there is only one concrete CredentialCache class which relies on in-memory caching. So assuming I'd like to stick with the current code base, should I implement an entire custom Authentication Provider in order to have a custom caching mechanism? What are your suggestions?

Many thanks,
Giorgi

**Comment by ginach** [comment]
The GetCacheBlob() method of CredentialCache will return the byte array representation of the cache for the app to store. The blob can be passed into the CredentialCache constructor to populate the cache at creation. This is modeled after [caching in ADAL](http://www.cloudidentity.com/blog/2013/10/01/getting-acquainted-with-adals-token-cache/). The main thing worth noting is the user ID would be needed to identify which credential to pull from the cache at authentication time.

**Comment by ginach** [comment]
I failed to mention in my previous answer that you can implement your own credential cache by inheriting from CredentialCache and overriding the respective methods.

**Comment by codeRecap** [comment]
Gina, thank you so much for the info, very helpful. I implemented the functionality using a refresh token, which is, I guess, a more elegant solution for my problem. It was all about re-authenticating the user without "bothering" him/her again. CredentialCache requires the user ID, which automatically means this class is not meant to be used as a re-authentication mechanism.

**Comment by ginach** [comment]
Glad you figured out a solution! Closing this issue.
