### ISSUE TITLE
Q: Does the SDK support proxy authentication?

### ISSUE THREAD

**Issue by Kyrodan** [OneDrive/onedrive-sdk-csharp#87]
Does this SDK support authentication behind a corporate proxy?
If yes: do you have a code snippet for that?

**Comment by ginach** [comment]
@Kyrodan, what type of app are you using? The default authentication implementations vary by platform.

**Comment by Kyrodan** [comment]
I'd like to implement a **WinForms** app that can use a proxy (with or without different authentication methods).
