### ISSUE TITLE
Get Files from SharePoint Sites

### ISSUE THREAD

**Issue by yuribb** [OneDrive/onedrive-sdk-csharp#90]
Hello. It is possible to get files from SharePoint Sites lists by using this library? In REST API request looks like "samplesite.sharepoint.com/MySubSite/_api/lists/getbytitle('MyDocuments')/Files"... Structure of this files equal to structure of files in OneDrive.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
