### ISSUE TITLE
File count varies by refresh token

### ISSUE THREAD

**Issue by mybluedog** [OneDrive/onedrive-sdk-csharp#93]
We have come across a strange bug (which could be in our code) where using a diffrerent refresh token  for the same user changes the number of files we can detect on a certain OneDrive (consumer account).

The file counts differ by refresh token, but are identical after multiple runs.  Neither of the refresh tokens returns the full count of files expected.

Our older refresh token returns 2,695 files every time.  A newly created token returns 20,757 files every time.  But according to the OndeDrive website, our OneDrive has ~30k files.

We are not getting exceptions from the API as we iterate over the files.

Q1: How can changing the refresh token (for the same user, who is the owner) change the file count?

Q2: I have searched the web trying to find what is the limit of files on a consumer OneDrive but it's ambiguous.  Can you please state the current file count limit for a free consumer drive?

**Comment by ginach** [comment]
This is an interesting one. Could you email me at ginach @ microsoft . com? I'm thinking this one could involve a lot of back and forth debugging.

**Comment by mybluedog** [comment]
It looks like we got our refresh tokens mixed up, and did not handle paging on our requests.
