### ISSUE TITLE
Feature request - filtering

### ISSUE THREAD

**Issue by mybluedog** [OneDrive/onedrive-sdk-csharp#96]
Should the request builder include a filter method, or is there some other way to do it?  I would like to be able to download just the files under a certain folder, or just the folders.  Right now it seems this is possible in REST but not from the C# API.  I also tried to do this using search, but had no luck.

**Comment by ginach** [comment]
Thanks for the feedback.

You can work around this right now by passing it to the request object. For example:

```csharp
var children = await client
    .Drive
    .Items[itemId]
    .Children
    .Request(new List<Option> { new QueryOption("filter", "folder%20ne%20null") })
    .GetAsync();
```

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
