### ISSUE TITLE
MVC Auth failed

### ISSUE THREAD

**Issue by andriipetrenko** [OneDrive/onedrive-sdk-csharp#98]
Hi, I'm going to use OneDrive for storing all clients uploaded files. So I'm going to use "internal" OneDrive credentials. The final User wouldn't have to sign in. I have to use my appID & secretID from the Web.config to sign in OneDrive and show all files for the final User. 
Is it possible? I try to use your sdk but it is not succesfull:

`var oneDriveClient = OneDriveClient.GetMicrosoftAccountClient(
                    APP_ID,
                    "http://I_dont_need_any_redirect_url.com/",
                    new[] { "wl.signin" },
                    APP_SECRET_ID);

await oneDriveClient.AuthenticateAsync();`

But I have an exception in this case: 
Code: _AuthenticationFailure_
Message: _Failed to retrieve a valid authentication token for the user._

**Comment by ginach** [comment]
Microsoft Account doesn't allow any app-only authentication flows and always requires the user be prompted to enter credentials at least for initial authentication.

What you'll probably want to do for your scenario is store the refresh token for the user and get a silently authenticated client using the token. [This webhooks sample](https://github.com/rgregg/onedrive-webhook-sample/tree/dev) is an example of an app that does this. You'll want to make sure to store the new refresh token returned anytime a new access token is retrieved. Refresh tokens are valid for up to a year.
